//
// Created by Ciaran on 06/11/2020.
//
#include "omexmeta/RDF.h"
#include "gtest/gtest.h"

using namespace omexmeta;

class CellMLTests : public ::testing::Test {
public:
    std::string cellml_example = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                 "<model xmlns=\"http://www.cellml.org/cellml/1.1#\" xmlns:cmeta=\"http://www.cellml.org/metadata/1.0#\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqs=\"http://www.cellml.org/bqs/1.0#\" xmlns:semsim=\"http://bime.uw.edu/semsim/#\" xmlns:dc=\"https://dublincore.org/specifications/dublin-core/dcmi-terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" name=\"annotation_examples\" cmeta:id=\"annExamples\">\n"
                                 "  <component name=\"main\">\n"
                                 "    <variable cmeta:id=\"main.Volume\" initial_value=\"100\" name=\"Volume\" units=\"dimensionless\" />\n"
                                 "    <variable cmeta:id=\"main.MembraneVoltage\" initial_value=\"-80\" name=\"MembraneVoltage\" units=\"dimensionless\" />\n"
                                 "    <variable cmeta:id=\"main.ReactionRate\" initial_value=\"1\" name=\"ReactionRate\" units=\"dimensionless\" />\n"
                                 "  </component>\n"
                                 "</model>";

    std::string cellml_example_annotation_xml = "<rdf:RDF\n"
                                                "    xmlns:semsim=\"http://bime.uw.edu/semsim/\"\n"
                                                "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                                                "    xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\"\n"
                                                "    xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\"\n"
                                                "    xmlns:dc=\"https://dublincore.org/specifications/dublin-core/dcmi-terms/\"\n"
                                                "    xmlns:myOMEX=\"http://omex-library.org/CellMLexamples.omex\"\n"
                                                "    xmlns:foaf=\"http://xmlns.com/foaf/0.1/\"\n"
                                                "    xmlns:local=\"http://omex-library.org/CellMLexamples.omex/examples.rdf\">\n"
                                                "  <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.cellml#main.ReactionRate\">\n"
                                                "    <bqbiol:isPropertyOf>\n"
                                                "      <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#process_0\">\n"
                                                "        <semsim:hasMediatorParticipant>\n"
                                                "          <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#mediator_0\">\n"
                                                "            <semsim:hasPhysicalEntityReference>\n"
                                                "              <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_12\">\n"
                                                "                <bqbiol:isPartOf>\n"
                                                "                  <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_9\">\n"
                                                "                    <bqbiol:isPartOf>\n"
                                                "                      <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_10\">\n"
                                                "                        <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:14515\"/>\n"
                                                "                      </rdf:Description>\n"
                                                "                    </bqbiol:isPartOf>\n"
                                                "                    <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:66836\"/>\n"
                                                "                  </rdf:Description>\n"
                                                "                </bqbiol:isPartOf>\n"
                                                "                <bqbiol:is rdf:resource=\"http://purl.obolibrary.org/obo/PR_000003767\"/>\n"
                                                "              </rdf:Description>\n"
                                                "            </semsim:hasPhysicalEntityReference>\n"
                                                "          </rdf:Description>\n"
                                                "        </semsim:hasMediatorParticipant>\n"
                                                "        <semsim:hasSinkParticipant>\n"
                                                "          <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#sink_1\"\n"
                                                "             semsim:hasMultiplier=\"1.0\">\n"
                                                "            <semsim:hasPhysicalEntityReference>\n"
                                                "              <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_11\">\n"
                                                "                <bqbiol:isPartOf rdf:resource=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_9\"/>\n"
                                                "                <bqbiol:is rdf:resource=\"https://identifiers.org/chebi/CHEBI:15343\"/>\n"
                                                "              </rdf:Description>\n"
                                                "            </semsim:hasPhysicalEntityReference>\n"
                                                "          </rdf:Description>\n"
                                                "        </semsim:hasSinkParticipant>\n"
                                                "        <semsim:hasSourceParticipant>\n"
                                                "          <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#source_1\"\n"
                                                "             semsim:hasMultiplier=\"1.0\">\n"
                                                "            <semsim:hasPhysicalEntityReference>\n"
                                                "              <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_8\">\n"
                                                "                <bqbiol:isPartOf rdf:resource=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_9\"/>\n"
                                                "                <bqbiol:is rdf:resource=\"https://identifiers.org/chebi/CHEBI:16236\"/>\n"
                                                "              </rdf:Description>\n"
                                                "            </semsim:hasPhysicalEntityReference>\n"
                                                "          </rdf:Description>\n"
                                                "        </semsim:hasSourceParticipant>\n"
                                                "        <semsim:name>my process</semsim:name>\n"
                                                "        <bqbiol:isVersionOf rdf:resource=\"http://identifiers.org/go/GO:0004022\"/>\n"
                                                "      </rdf:Description>\n"
                                                "    </bqbiol:isPropertyOf>\n"
                                                "    <bqbiol:isVersionOf rdf:resource=\"https://identifiers.org/opb/OPB_00592\"/>\n"
                                                "  </rdf:Description>\n"
                                                "  <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.cellml#main.Volume\">\n"
                                                "    <bqbiol:isPropertyOf>\n"
                                                "      <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_0\">\n"
                                                "        <bqbiol:isPartOf>\n"
                                                "          <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_1\">\n"
                                                "            <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:18228\"/>\n"
                                                "          </rdf:Description>\n"
                                                "        </bqbiol:isPartOf>\n"
                                                "        <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:9670\"/>\n"
                                                "      </rdf:Description>\n"
                                                "    </bqbiol:isPropertyOf>\n"
                                                "    <bqbiol:isVersionOf rdf:resource=\"https://identifiers.org/opb/OPB_00154\"/>\n"
                                                "  </rdf:Description>\n"
                                                "  <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.cellml\"\n"
                                                "     semsim:modelName=\"annotation_examples\"/>\n"
                                                "  <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.cellml#main.MembraneVoltage\">\n"
                                                "    <bqbiol:isPropertyOf>\n"
                                                "      <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#force_0\">\n"
                                                "        <semsim:hasSinkParticipant>\n"
                                                "          <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#sink_0\">\n"
                                                "            <semsim:hasPhysicalEntityReference>\n"
                                                "              <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_5\">\n"
                                                "                <bqbiol:isPartOf>\n"
                                                "                  <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_6\">\n"
                                                "                    <bqbiol:isPartOf>\n"
                                                "                      <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_7\">\n"
                                                "                        <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:16016\"/>\n"
                                                "                      </rdf:Description>\n"
                                                "                    </bqbiol:isPartOf>\n"
                                                "                    <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:9672\"/>\n"
                                                "                  </rdf:Description>\n"
                                                "                </bqbiol:isPartOf>\n"
                                                "                <bqbiol:is rdf:resource=\"https://identifiers.org/chebi/CHEBI:24870\"/>\n"
                                                "              </rdf:Description>\n"
                                                "            </semsim:hasPhysicalEntityReference>\n"
                                                "          </rdf:Description>\n"
                                                "        </semsim:hasSinkParticipant>\n"
                                                "        <semsim:hasSourceParticipant>\n"
                                                "          <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#source_0\">\n"
                                                "            <semsim:hasPhysicalEntityReference>\n"
                                                "              <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_2\">\n"
                                                "                <bqbiol:isPartOf>\n"
                                                "                  <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_3\">\n"
                                                "                    <bqbiol:isPartOf>\n"
                                                "                      <rdf:Description rdf:about=\"http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_4\">\n"
                                                "                        <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:70586\"/>\n"
                                                "                      </rdf:Description>\n"
                                                "                    </bqbiol:isPartOf>\n"
                                                "                    <bqbiol:is rdf:resource=\"http://identifiers.org/fma/FMA:66836\"/>\n"
                                                "                  </rdf:Description>\n"
                                                "                </bqbiol:isPartOf>\n"
                                                "                <bqbiol:is rdf:resource=\"https://identifiers.org/chebi/CHEBI:24870\"/>\n"
                                                "              </rdf:Description>\n"
                                                "            </semsim:hasPhysicalEntityReference>\n"
                                                "          </rdf:Description>\n"
                                                "        </semsim:hasSourceParticipant>\n"
                                                "      </rdf:Description>\n"
                                                "    </bqbiol:isPropertyOf>\n"
                                                "    <bqbiol:isVersionOf rdf:resource=\"https://identifiers.org/opb/OPB_00506\"/>\n"
                                                "  </rdf:Description>\n"
                                                "</rdf:RDF>";

    std::string cellml_example_annotation_turtle = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                                                   "@prefix semsim: <http://bime.uw.edu/semsim/> .\n"
                                                   "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                                                   "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                                                   "@prefix dc: <https://dublincore.org/specifications/dublin-core/dcmi-terms/> .\n"
                                                   "@prefix foaf: <http://xmlns.com/foaf/0.1/> .\n"
                                                   "@prefix OMEXlib: <http://omex-library.org/> .\n"
                                                   "@prefix myOMEX: <http://omex-library.org/NewOmex.omex/> .\n"
                                                   "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.cellml>\n"
                                                   "    semsim:modelName \"annotation_examples\" .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.cellml#main.MembraneVoltage>\n"
                                                   "    bqbiol:isPropertyOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#force_0> ;\n"
                                                   "    bqbiol:isVersionOf <https://identifiers.org/opb/OPB_00506> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.cellml#main.ReactionRate>\n"
                                                   "    bqbiol:isPropertyOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#process_0> ;\n"
                                                   "    bqbiol:isVersionOf <https://identifiers.org/opb/OPB_00592> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.cellml#main.Volume>\n"
                                                   "    bqbiol:isPropertyOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_0> ;\n"
                                                   "    bqbiol:isVersionOf <https://identifiers.org/opb/OPB_00154> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_0>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:9670> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_1> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_1>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:18228> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_10>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:14515> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_11>\n"
                                                   "    bqbiol:is <https://identifiers.org/chebi/CHEBI:15343> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_9> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_12>\n"
                                                   "    bqbiol:is <http://purl.obolibrary.org/obo/PR_000003767> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_9> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_2>\n"
                                                   "    bqbiol:is <https://identifiers.org/chebi/CHEBI:24870> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_3> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_3>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:66836> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_4> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_4>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:70586> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_5>\n"
                                                   "    bqbiol:is <https://identifiers.org/chebi/CHEBI:24870> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_6> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_6>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:9672> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_7> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_7>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:16016> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_8>\n"
                                                   "    bqbiol:is <https://identifiers.org/chebi/CHEBI:16236> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_9> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_9>\n"
                                                   "    bqbiol:is <http://identifiers.org/fma/FMA:66836> ;\n"
                                                   "    bqbiol:isPartOf <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_10> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#force_0>\n"
                                                   "    semsim:hasSinkParticipant <http://omex-library.org/CellMLexamples.omex/examples.rdf#sink_0> ;\n"
                                                   "    semsim:hasSourceParticipant <http://omex-library.org/CellMLexamples.omex/examples.rdf#source_0> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#mediator_0>\n"
                                                   "    semsim:hasPhysicalEntityReference <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_12> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#process_0>\n"
                                                   "    semsim:hasMediatorParticipant <http://omex-library.org/CellMLexamples.omex/examples.rdf#mediator_0> ;\n"
                                                   "    semsim:hasSinkParticipant <http://omex-library.org/CellMLexamples.omex/examples.rdf#sink_1> ;\n"
                                                   "    semsim:hasSourceParticipant <http://omex-library.org/CellMLexamples.omex/examples.rdf#source_1> ;\n"
                                                   "    semsim:name \"my process\" ;\n"
                                                   "    bqbiol:isVersionOf <http://identifiers.org/go/GO:0004022> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#sink_0>\n"
                                                   "    semsim:hasPhysicalEntityReference <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_5> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#sink_1>\n"
                                                   "    semsim:hasMultiplier \"1.0\" ;\n"
                                                   "    semsim:hasPhysicalEntityReference <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_11> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#source_0>\n"
                                                   "    semsim:hasPhysicalEntityReference <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_2> .\n"
                                                   "\n"
                                                   "<http://omex-library.org/CellMLexamples.omex/examples.rdf#source_1>\n"
                                                   "    semsim:hasMultiplier \"1.0\" ;\n"
                                                   "    semsim:hasPhysicalEntityReference <http://omex-library.org/CellMLexamples.omex/examples.rdf#entity_8> .";

    CellMLTests() = default;
};


TEST_F(CellMLTests, TestThatXMLAndTurtleAreEqual) {
    ASSERT_TRUE(RDF::equals(cellml_example_annotation_xml, cellml_example_annotation_turtle, "rdfxml", "turtle"));
}

TEST_F(CellMLTests, t){
    RDF rdf = RDF::fromString(cellml_example);
    rdf.toFile("cellml_example_annotation_turtle.rdf");
}
TEST_F(CellMLTests, Test){
    RDF rdf;
    Editor editor = rdf.toEditor(cellml_example, false, false);

    editor.newPhysicalEntity();
}



















