//
// Created by Ciaran on 20/04/2021.
//
#include "MockRDF.h"
#include "SBMLFactory.h"
#include "omexmeta/PurgeRDFBag.h"
#include "omexmeta/RDF.h"
#include "gtest/gtest.h"
#include <omexmeta/Options.h>

using namespace omexmeta;

class PurgeRDFBagTests : public ::testing::Test {
public:
    MockRDF mockRdf;



    // note, this string is post "vcard -> foaf" processing
    PurgeRDFBagTests() {
        Options::translateVCard_ = false;// we'll do it manually during tests

    };


    void checkRDFBagIsPurged(const std::string &inputString, const std::string &inputSyntax, const std::string& expected, const std::string& expectedSyntax = "turtle" ) {
        RDF rdf = RDF::fromString(inputString, inputSyntax);
        PurgeRDFBag purgeRdfBag(&rdf);
        purgeRdfBag.purge();
        ASSERT_TRUE(RDF::equals(&rdf, expected, expectedSyntax, true));
    }

};


TEST_F(PurgeRDFBagTests, WithRDFBagLists) {
    std::string expected = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                           "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                           "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                           "@prefix OMEXlib: <http://omex-library.org/> .\n"
                           "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                           "\n"
                           "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                           "    <http://purl.org/dc/elements/1.1/creator> [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"EMBL-EBI\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Chelliah\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Vijayalakshmi\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"viji@ebi.ac.uk\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"\"\"Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                           "                                    Potsdam, Germany\n"
                           "                                \"\"\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Nikoloski\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Zoran\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"nikoloski@mpimp-golm.mpg.de\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"Max-Planck-Institute of Molecular Plant Physiology\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Arnold\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Anne\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"arnold@mpimp-golm.mpg.de\"\n"
                           "    ] .";
    std::string inputWithLists = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                                 "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                                 "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                                 "@prefix OMEXlib: <http://omex-library.org/> .\n"
                                 "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                                 "\n"
                                 "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                                 "    <http://purl.org/dc/elements/1.1/creator> [\n"
                                 "        rdf:_1 [\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#EMAIL> \"viji@ebi.ac.uk\" ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#N> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Family> \"Chelliah\" ;\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Given> \"Vijayalakshmi\"\n"
                                 "            ] ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#ORG> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Orgname> \"EMBL-EBI\"\n"
                                 "            ]\n"
                                 "        ] ;\n"
                                 "        rdf:_2 [\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#EMAIL> \"nikoloski@mpimp-golm.mpg.de\" ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#N> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Family> \"Nikoloski\" ;\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Given> \"Zoran\"\n"
                                 "            ] ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#ORG> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Orgname> \"\"\"Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                                 "                                    Potsdam, Germany\n"
                                 "                                \"\"\"\n"
                                 "            ]\n"
                                 "        ] ;\n"
                                 "        rdf:_3 [\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#EMAIL> \"arnold@mpimp-golm.mpg.de\" ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#N> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Family> \"Arnold\" ;\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Given> \"Anne\"\n"
                                 "            ] ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#ORG> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Orgname> \"Max-Planck-Institute of Molecular Plant Physiology\"\n"
                                 "            ]\n"
                                 "        ] ;\n"
                                 "        a rdf:Bag\n"
                                 "    ] .";
    RDF rdf = RDF::fromString(inputWithLists);
    PurgeRDFBag purgeRdfBag(&rdf);
    purgeRdfBag.purgeListBagEntries();
    //    purgeRdfBag.purgeNonListBagEntries();
    std::cout << rdf.toString() << std::endl;

    ASSERT_TRUE(RDF::equals(&rdf, expected, "turtle", true));
}

TEST_F(PurgeRDFBagTests, WithOutRDFBagLists) {
    std::string expected = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                           "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                           "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                           "@prefix OMEXlib: <http://omex-library.org/> .\n"
                           "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                           "\n"
                           "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                           "    bqbiol:hasTaxon <http://identifiers.org/taxonomy/33090> ;\n"
                           "    bqmodel:is <http://identifiers.org/biomodels.db/BIOMD0000000385>, <http://identifiers.org/biomodels.db/MODEL1109270001>, <http://identifiers.org/obo.go/GO:0019253> ;\n"
                           "    bqmodel:isDescribedBy <http://identifiers.org/pubmed/22001849> ;\n"
                           "    <http://purl.org/dc/terms/created> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2011-10-19T14:51:13Z\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/modified> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2012-04-20T19:52:45Z\"\n"
                           "    ] .";

    std::string inputWithoutLists = "<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                                    "                 xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\"\n"
                                    "                 xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
                                    "                 xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
                                    "            <rdf:Description rdf:about=\"#_272044\">\n"
                                    "                <dcterms:created rdf:parseType=\"Resource\">\n"
                                    "                    <dcterms:W3CDTF>2011-10-19T14:51:13Z</dcterms:W3CDTF>\n"
                                    "                </dcterms:created>\n"
                                    "                <dcterms:modified rdf:parseType=\"Resource\">\n"
                                    "                    <dcterms:W3CDTF>2012-04-20T19:52:45Z</dcterms:W3CDTF>\n"
                                    "                </dcterms:modified>\n"
                                    "                <bqmodel:is>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL1109270001\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:is>\n"
                                    "                <bqmodel:is>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000385\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:is>\n"
                                    "                <bqmodel:isDescribedBy>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/pubmed/22001849\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:isDescribedBy>\n"
                                    "                <bqmodel:is>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0019253\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:is>\n"
                                    "                <bqbiol:hasTaxon>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/33090\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqbiol:hasTaxon>\n"
                                    "            </rdf:Description>\n"
                                    "        </rdf:RDF>";


    RDF rdf = RDF::fromString(inputWithoutLists);
    PurgeRDFBag purgeRdfBag(&rdf);
    //    purgeRdfBag.purgeListBagEntries();
    purgeRdfBag.purgeNonListBagEntries();
    std::cout << rdf.toString() << std::endl;
    ASSERT_TRUE(RDF::equals(&rdf, expected, "turtle", true));
}

TEST_F(PurgeRDFBagTests, BothWithAndWithoutRdfBagLists) {
    std::string expected = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                           "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                           "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                           "@prefix OMEXlib: <http://omex-library.org/> .\n"
                           "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                           "\n"
                           "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                           "    bqbiol:hasTaxon <http://identifiers.org/taxonomy/33090> ;\n"
                           "    bqmodel:is <http://identifiers.org/biomodels.db/BIOMD0000000385>, <http://identifiers.org/biomodels.db/MODEL1109270001>, <http://identifiers.org/obo.go/GO:0019253> ;\n"
                           "    bqmodel:isDescribedBy <http://identifiers.org/pubmed/22001849> ;\n"
                           "    <http://purl.org/dc/elements/1.1/creator> [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"EMBL-EBI\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Chelliah\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Vijayalakshmi\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"viji@ebi.ac.uk\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"\"\"Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                           "                                    Potsdam, Germany\n"
                           "                                \"\"\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Nikoloski\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Zoran\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"nikoloski@mpimp-golm.mpg.de\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"Max-Planck-Institute of Molecular Plant Physiology\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Arnold\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Anne\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"arnold@mpimp-golm.mpg.de\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/created> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2011-10-19T14:51:13Z\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/modified> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2012-04-20T19:52:45Z\"\n"
                           "    ] .";
    std::string fullInput = "<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                            "                 xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\"\n"
                            "                 xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
                            "                 xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
                            "            <rdf:Description rdf:about=\"#_272044\">\n"
                            "                <dc:creator>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:parseType=\"Resource\">\n"
                            "                            <vCard:N rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Family>Chelliah</vCard:Family>\n"
                            "                                <vCard:Given>Vijayalakshmi</vCard:Given>\n"
                            "                            </vCard:N>\n"
                            "                            <vCard:EMAIL>viji@ebi.ac.uk</vCard:EMAIL>\n"
                            "                            <vCard:ORG rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Orgname>EMBL-EBI</vCard:Orgname>\n"
                            "                            </vCard:ORG>\n"
                            "                        </rdf:li>\n"
                            "                        <rdf:li rdf:parseType=\"Resource\">\n"
                            "                            <vCard:N rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Family>Nikoloski</vCard:Family>\n"
                            "                                <vCard:Given>Zoran</vCard:Given>\n"
                            "                            </vCard:N>\n"
                            "                            <vCard:EMAIL>nikoloski@mpimp-golm.mpg.de</vCard:EMAIL>\n"
                            "                            <vCard:ORG rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Orgname>Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                            "                                    Potsdam, Germany\n"
                            "                                </vCard:Orgname>\n"
                            "                            </vCard:ORG>\n"
                            "                        </rdf:li>\n"
                            "                        <rdf:li rdf:parseType=\"Resource\">\n"
                            "                            <vCard:N rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Family>Arnold</vCard:Family>\n"
                            "                                <vCard:Given>Anne</vCard:Given>\n"
                            "                            </vCard:N>\n"
                            "                            <vCard:EMAIL>arnold@mpimp-golm.mpg.de</vCard:EMAIL>\n"
                            "                            <vCard:ORG rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Orgname>Max-Planck-Institute of Molecular Plant Physiology</vCard:Orgname>\n"
                            "                            </vCard:ORG>\n"
                            "                        </rdf:li>\n"
                            "                    </rdf:Bag>\n"
                            "                </dc:creator>\n"
                            "                <dcterms:created rdf:parseType=\"Resource\">\n"
                            "                    <dcterms:W3CDTF>2011-10-19T14:51:13Z</dcterms:W3CDTF>\n"
                            "                </dcterms:created>\n"
                            "                <dcterms:modified rdf:parseType=\"Resource\">\n"
                            "                    <dcterms:W3CDTF>2012-04-20T19:52:45Z</dcterms:W3CDTF>\n"
                            "                </dcterms:modified>\n"
                            "                <bqmodel:is>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL1109270001\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:is>\n"
                            "                <bqmodel:is>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000385\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:is>\n"
                            "                <bqmodel:isDescribedBy>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/pubmed/22001849\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:isDescribedBy>\n"
                            "                <bqmodel:is>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0019253\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:is>\n"
                            "                <bqbiol:hasTaxon>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/33090\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqbiol:hasTaxon>\n"
                            "            </rdf:Description>\n"
                            "        </rdf:RDF>";
    checkRDFBagIsPurged(fullInput, "rdfxml", expected, "turtle");

    RDF rdf = RDF::fromString(fullInput);
    std::cout << rdf.toString("turtle") << std::endl;
}


TEST_F(PurgeRDFBagTests, Input21) {
    std::string creatorInput = "<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
                               "         xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\"\n"
                               "         xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\"\n"
                               "         xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\">\n"
                               "    <rdf:Description rdf:about=\"#COPASI0\">\n"
                               "        <dc:creator>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:parseType=\"Resource\">\n"
                               "                    <vCard:N rdf:parseType=\"Resource\">\n"
                               "                        <vCard:Family>Kothamachu</vCard:Family>\n"
                               "                        <vCard:Given>Varun</vCard:Given>\n"
                               "                    </vCard:N>\n"
                               "                    <vCard:EMAIL>kothamav@babraham.ac.uk</vCard:EMAIL>\n"
                               "                    <vCard:ORG rdf:parseType=\"Resource\">\n"
                               "                        <vCard:Orgname>Babraham Institute</vCard:Orgname>\n"
                               "                    </vCard:ORG>\n"
                               "                </rdf:li>\n"
                               "                <rdf:li rdf:parseType=\"Resource\">\n"
                               "                    <vCard:N rdf:parseType=\"Resource\">\n"
                               "                        <vCard:Family>Debjit</vCard:Family>\n"
                               "                        <vCard:Given>Ray</vCard:Given>\n"
                               "                    </vCard:N>\n"
                               "                    <vCard:EMAIL>debjit.ray@email.wsu.edu</vCard:EMAIL>\n"
                               "                    <vCard:ORG rdf:parseType=\"Resource\">\n"
                               "                        <vCard:Orgname>Washington State University</vCard:Orgname>\n"
                               "                    </vCard:ORG>\n"
                               "                </rdf:li>\n"
                               "                <rdf:li rdf:parseType=\"Resource\">\n"
                               "                    <vCard:N rdf:parseType=\"Resource\">\n"
                               "                        <vCard:Family>Karakurt</vCard:Family>\n"
                               "                        <vCard:Given>Hamza Umut</vCard:Given>\n"
                               "                    </vCard:N>\n"
                               "                    <vCard:EMAIL>hkarakurt@gtu.edu.tr</vCard:EMAIL>\n"
                               "                    <vCard:ORG rdf:parseType=\"Resource\">\n"
                               "                        <vCard:Orgname>Gebze Technical University</vCard:Orgname>\n"
                               "                    </vCard:ORG>\n"
                               "                </rdf:li>\n"
                               "            </rdf:Bag>\n"
                               "        </dc:creator>\n"
                               "        <dcterms:created rdf:parseType=\"Resource\">\n"
                               "            <dcterms:W3CDTF>2017-02-03T14:41:35Z</dcterms:W3CDTF>\n"
                               "        </dcterms:created>\n"
                               "        <dcterms:modified rdf:parseType=\"Resource\">\n"
                               "            <dcterms:W3CDTF>2017-06-13T16:22:29Z</dcterms:W3CDTF>\n"
                               "        </dcterms:modified>\n"
                               "        <bqmodel:is>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL1303060000\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </bqmodel:is>\n"
                               "        <bqmodel:is>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000626\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </bqmodel:is>\n"
                               "        <bqmodel:isDescribedBy>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/pubmed/23631506\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </bqmodel:isDescribedBy>\n"
                               "        <bqbiol:isVersionOf>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/go/GO:0040020\"/>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/go/GO:0051321\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </bqbiol:isVersionOf>\n"
                               "        <bqbiol:hasTaxon>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/4932\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </bqbiol:hasTaxon>\n"
                               "        <bqbiol:isDescribedBy>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/eco/ECO:0000362\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </bqbiol:isDescribedBy>\n"
                               "        <bqbiol:hasProperty>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/mamo/MAMO_0000046\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </bqbiol:hasProperty>\n"
                               "    </rdf:Description>\n"
                               "</rdf:RDF>";

    std::string expected = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                           "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                           "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                           "@prefix OMEXlib: <http://omex-library.org/> .\n"
                           "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                           "\n"
                           "<http://omex-library.org/NewOmex.omex/NewModel.xml#COPASI0>\n"
                           "    bqbiol:hasProperty <http://identifiers.org/mamo/MAMO_0000046> ;\n"
                           "    bqbiol:hasTaxon <http://identifiers.org/taxonomy/4932> ;\n"
                           "    bqbiol:isDescribedBy <http://identifiers.org/eco/ECO:0000362> ;\n"
                           "    bqbiol:isVersionOf <http://identifiers.org/go/GO:0040020>, <http://identifiers.org/go/GO:0051321> ;\n"
                           "    bqmodel:is <http://identifiers.org/biomodels.db/BIOMD0000000626>, <http://identifiers.org/biomodels.db/MODEL1303060000> ;\n"
                           "    bqmodel:isDescribedBy <http://identifiers.org/pubmed/23631506> ;\n"
                           "    <http://purl.org/dc/elements/1.1/creator> [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"Babraham Institute\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Kothamachu\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Varun\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"kothamav@babraham.ac.uk\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"Washington State University\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Debjit\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Ray\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"debjit.ray@email.wsu.edu\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"Gebze Technical University\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Karakurt\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Hamza Umut\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"hkarakurt@gtu.edu.tr\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/created> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2017-02-03T14:41:35Z\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/modified> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2017-06-13T16:22:29Z\"\n"
                           "    ] .\n";

    RDF rdf = RDF::fromString(creatorInput, "rdfxml");
    PurgeRDFBag purgeRdfBag(&rdf);
    purgeRdfBag.purgeListBagEntries();
    purgeRdfBag.purgeNonListBagEntries();
    std::cout << rdf.toString("turtle") << std::endl;
    RDF::equals(&rdf, expected);
}
TEST_F(PurgeRDFBagTests, Input22) {
    std::string creatorInput = "<rdf:RDF xmlns:CopasiMT=\"http://www.copasi.org/RDF/MiriamTerms#\"\n"
                               "         xmlns:dcterms=\"http://purl.org/dc/terms/\"\n"
                               "         xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                               "         xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\">\n"
                               "    <rdf:Description rdf:about=\"#COPASI0\">\n"
                               "        <dcterms:bibliographicCitation>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li>\n"
                               "                    <rdf:Description>\n"
                               "                        <CopasiMT:isDescribedBy rdf:resource=\"http://identifiers.org/pubmed/23631506\"/>\n"
                               "                    </rdf:Description>\n"
                               "                </rdf:li>\n"
                               "            </rdf:Bag>\n"
                               "        </dcterms:bibliographicCitation>\n"
                               "        <dcterms:created>\n"
                               "            <rdf:Description>\n"
                               "                <dcterms:W3CDTF>2017-02-03T14:41:35Z</dcterms:W3CDTF>\n"
                               "            </rdf:Description>\n"
                               "        </dcterms:created>\n"
                               "        <dcterms:creator>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li>\n"
                               "                    <rdf:Description>\n"
                               "                        <vCard:EMAIL>kothamav@babraham.ac.uk</vCard:EMAIL>\n"
                               "                        <vCard:N>\n"
                               "                            <rdf:Description>\n"
                               "                                <vCard:Family>Kothamachu</vCard:Family>\n"
                               "                                <vCard:Given>Varun</vCard:Given>\n"
                               "                            </rdf:Description>\n"
                               "                        </vCard:N>\n"
                               "                        <vCard:ORG>\n"
                               "                            <rdf:Description>\n"
                               "                                <vCard:Orgname>Babraham Institute</vCard:Orgname>\n"
                               "                            </rdf:Description>\n"
                               "                        </vCard:ORG>\n"
                               "                    </rdf:Description>\n"
                               "                </rdf:li>\n"
                               "                <rdf:li>\n"
                               "                    <rdf:Description>\n"
                               "                        <vCard:EMAIL>hkarakurt@gtu.edu.tr</vCard:EMAIL>\n"
                               "                        <vCard:N>\n"
                               "                            <rdf:Description>\n"
                               "                                <vCard:Family>Karakurt</vCard:Family>\n"
                               "                                <vCard:Given>Hamza Umut</vCard:Given>\n"
                               "                            </rdf:Description>\n"
                               "                        </vCard:N>\n"
                               "                        <vCard:ORG>\n"
                               "                            <rdf:Description>\n"
                               "                                <vCard:Orgname>Gebze Technical University</vCard:Orgname>\n"
                               "                            </rdf:Description>\n"
                               "                        </vCard:ORG>\n"
                               "                    </rdf:Description>\n"
                               "                </rdf:li>\n"
                               "                <rdf:li>\n"
                               "                    <rdf:Description>\n"
                               "                        <vCard:EMAIL>debjit.ray@email.wsu.edu</vCard:EMAIL>\n"
                               "                        <vCard:N>\n"
                               "                            <rdf:Description>\n"
                               "                                <vCard:Family>Debjit</vCard:Family>\n"
                               "                                <vCard:Given>Ray</vCard:Given>\n"
                               "                            </rdf:Description>\n"
                               "                        </vCard:N>\n"
                               "                        <vCard:ORG>\n"
                               "                            <rdf:Description>\n"
                               "                                <vCard:Orgname>Washington State University</vCard:Orgname>\n"
                               "                            </rdf:Description>\n"
                               "                        </vCard:ORG>\n"
                               "                    </rdf:Description>\n"
                               "                </rdf:li>\n"
                               "            </rdf:Bag>\n"
                               "        </dcterms:creator>\n"
                               "        <dcterms:modified>\n"
                               "            <rdf:Description>\n"
                               "                <dcterms:W3CDTF>2017-02-24T13:27:01Z</dcterms:W3CDTF>\n"
                               "            </rdf:Description>\n"
                               "        </dcterms:modified>\n"
                               "        <CopasiMT:is>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL1303060000\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </CopasiMT:is>\n"
                               "        <CopasiMT:is>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000626\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </CopasiMT:is>\n"
                               "        <CopasiMT:is>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/eco/ECO:0000362\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </CopasiMT:is>\n"
                               "        <CopasiMT:is>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"urn:miriam:reactome:R-SCE-1500620\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </CopasiMT:is>\n"
                               "        <CopasiMT:is>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/mamo/MAMO_0000046\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </CopasiMT:is>\n"
                               "        <CopasiMT:isVersionOf>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"urn:miriam:go:GO:0051321\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </CopasiMT:isVersionOf>\n"
                               "        <CopasiMT:isVersionOf>\n"
                               "            <rdf:Bag>\n"
                               "                <rdf:li rdf:resource=\"http://identifiers.org/go/GO:0040020\"/>\n"
                               "            </rdf:Bag>\n"
                               "        </CopasiMT:isVersionOf>\n"
                               "    </rdf:Description>\n"
                               "</rdf:RDF>";

    std::string expected = "";

    RDF rdf = RDF::fromString(creatorInput, "rdfxml");
    PurgeRDFBag purgeRdfBag(&rdf);
//    purgeRdfBag.purgeListBagEntries();
//    purgeRdfBag.purgeNonListBagEntries();
    std::cout << rdf.toString("turtle") << std::endl;
//    RDF::equals(&rdf, expected);
}
