//
// Created by Ciaran on 20/04/2021.
//
#include "omexmeta/PurgeRDFBag.h"
#include "omexmeta/RDF.h"
#include "gtest/gtest.h"

using namespace omexmeta;

class PurgeRDFBagTests : public ::testing::Test {
public:
    std::string fullInput = "<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                            "                 xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\"\n"
                            "                 xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
                            "                 xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
                            "            <rdf:Description rdf:about=\"#_272044\">\n"
                            "                <dc:creator>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:parseType=\"Resource\">\n"
                            "                            <vCard:N rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Family>Chelliah</vCard:Family>\n"
                            "                                <vCard:Given>Vijayalakshmi</vCard:Given>\n"
                            "                            </vCard:N>\n"
                            "                            <vCard:EMAIL>viji@ebi.ac.uk</vCard:EMAIL>\n"
                            "                            <vCard:ORG rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Orgname>EMBL-EBI</vCard:Orgname>\n"
                            "                            </vCard:ORG>\n"
                            "                        </rdf:li>\n"
                            "                        <rdf:li rdf:parseType=\"Resource\">\n"
                            "                            <vCard:N rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Family>Nikoloski</vCard:Family>\n"
                            "                                <vCard:Given>Zoran</vCard:Given>\n"
                            "                            </vCard:N>\n"
                            "                            <vCard:EMAIL>nikoloski@mpimp-golm.mpg.de</vCard:EMAIL>\n"
                            "                            <vCard:ORG rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Orgname>Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                            "                                    Potsdam, Germany\n"
                            "                                </vCard:Orgname>\n"
                            "                            </vCard:ORG>\n"
                            "                        </rdf:li>\n"
                            "                        <rdf:li rdf:parseType=\"Resource\">\n"
                            "                            <vCard:N rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Family>Arnold</vCard:Family>\n"
                            "                                <vCard:Given>Anne</vCard:Given>\n"
                            "                            </vCard:N>\n"
                            "                            <vCard:EMAIL>arnold@mpimp-golm.mpg.de</vCard:EMAIL>\n"
                            "                            <vCard:ORG rdf:parseType=\"Resource\">\n"
                            "                                <vCard:Orgname>Max-Planck-Institute of Molecular Plant Physiology</vCard:Orgname>\n"
                            "                            </vCard:ORG>\n"
                            "                        </rdf:li>\n"
                            "                    </rdf:Bag>\n"
                            "                </dc:creator>\n"
                            "                <dcterms:created rdf:parseType=\"Resource\">\n"
                            "                    <dcterms:W3CDTF>2011-10-19T14:51:13Z</dcterms:W3CDTF>\n"
                            "                </dcterms:created>\n"
                            "                <dcterms:modified rdf:parseType=\"Resource\">\n"
                            "                    <dcterms:W3CDTF>2012-04-20T19:52:45Z</dcterms:W3CDTF>\n"
                            "                </dcterms:modified>\n"
                            "                <bqmodel:is>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL1109270001\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:is>\n"
                            "                <bqmodel:is>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000385\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:is>\n"
                            "                <bqmodel:isDescribedBy>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/pubmed/22001849\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:isDescribedBy>\n"
                            "                <bqmodel:is>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0019253\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqmodel:is>\n"
                            "                <bqbiol:hasTaxon>\n"
                            "                    <rdf:Bag>\n"
                            "                        <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/33090\"/>\n"
                            "                    </rdf:Bag>\n"
                            "                </bqbiol:hasTaxon>\n"
                            "            </rdf:Description>\n"
                            "        </rdf:RDF>";
    std::string inputWithLists = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                                 "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                                 "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                                 "@prefix OMEXlib: <http://omex-library.org/> .\n"
                                 "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                                 "\n"
                                 "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                                 "    <http://purl.org/dc/elements/1.1/creator> [\n"
                                 "        rdf:_1 [\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#EMAIL> \"viji@ebi.ac.uk\" ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#N> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Family> \"Chelliah\" ;\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Given> \"Vijayalakshmi\"\n"
                                 "            ] ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#ORG> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Orgname> \"EMBL-EBI\"\n"
                                 "            ]\n"
                                 "        ] ;\n"
                                 "        rdf:_2 [\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#EMAIL> \"nikoloski@mpimp-golm.mpg.de\" ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#N> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Family> \"Nikoloski\" ;\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Given> \"Zoran\"\n"
                                 "            ] ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#ORG> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Orgname> \"\"\"Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                                 "                                    Potsdam, Germany\n"
                                 "                                \"\"\"\n"
                                 "            ]\n"
                                 "        ] ;\n"
                                 "        rdf:_3 [\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#EMAIL> \"arnold@mpimp-golm.mpg.de\" ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#N> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Family> \"Arnold\" ;\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Given> \"Anne\"\n"
                                 "            ] ;\n"
                                 "            <http://www.w3.org/2001/vcard-rdf/3.0#ORG> [\n"
                                 "                <http://www.w3.org/2001/vcard-rdf/3.0#Orgname> \"Max-Planck-Institute of Molecular Plant Physiology\"\n"
                                 "            ]\n"
                                 "        ] ;\n"
                                 "        a rdf:Bag\n"
                                 "    ] .";

    std::string inputWithoutLists = "<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                                    "                 xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\"\n"
                                    "                 xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
                                    "                 xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
                                    "            <rdf:Description rdf:about=\"#_272044\">\n"
                                    "                <dcterms:created rdf:parseType=\"Resource\">\n"
                                    "                    <dcterms:W3CDTF>2011-10-19T14:51:13Z</dcterms:W3CDTF>\n"
                                    "                </dcterms:created>\n"
                                    "                <dcterms:modified rdf:parseType=\"Resource\">\n"
                                    "                    <dcterms:W3CDTF>2012-04-20T19:52:45Z</dcterms:W3CDTF>\n"
                                    "                </dcterms:modified>\n"
                                    "                <bqmodel:is>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL1109270001\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:is>\n"
                                    "                <bqmodel:is>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000385\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:is>\n"
                                    "                <bqmodel:isDescribedBy>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/pubmed/22001849\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:isDescribedBy>\n"
                                    "                <bqmodel:is>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0019253\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqmodel:is>\n"
                                    "                <bqbiol:hasTaxon>\n"
                                    "                    <rdf:Bag>\n"
                                    "                        <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/33090\"/>\n"
                                    "                    </rdf:Bag>\n"
                                    "                </bqbiol:hasTaxon>\n"
                                    "            </rdf:Description>\n"
                                    "        </rdf:RDF>";

    PurgeRDFBagTests() = default;
};


TEST_F(PurgeRDFBagTests, WithRDFBagLists) {
    std::string expected = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                           "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                           "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                           "@prefix OMEXlib: <http://omex-library.org/> .\n"
                           "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                           "\n"
                           "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                           "    <http://purl.org/dc/elements/1.1/creator> [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"EMBL-EBI\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Chelliah\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Vijayalakshmi\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"viji@ebi.ac.uk\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"\"\"Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                           "                                    Potsdam, Germany\n"
                           "                                \"\"\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Nikoloski\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Zoran\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"nikoloski@mpimp-golm.mpg.de\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"Max-Planck-Institute of Molecular Plant Physiology\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Arnold\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Anne\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"arnold@mpimp-golm.mpg.de\"\n"
                           "    ] .";
    RDF rdf = RDF::fromString(inputWithLists);

    std::cout << rdf.toString() << std::endl;

    ASSERT_TRUE(RDF::equals(&rdf, expected, "turtle", true));
}

TEST_F(PurgeRDFBagTests, WithOutRDFBagLists) {
    std::string expected = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                           "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                           "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                           "@prefix OMEXlib: <http://omex-library.org/> .\n"
                           "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                           "\n"
                           "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                           "    bqbiol:hasTaxon <http://identifiers.org/taxonomy/33090> ;\n"
                           "    bqmodel:is <http://identifiers.org/biomodels.db/BIOMD0000000385>, <http://identifiers.org/biomodels.db/MODEL1109270001>, <http://identifiers.org/obo.go/GO:0019253> ;\n"
                           "    bqmodel:isDescribedBy <http://identifiers.org/pubmed/22001849> ;\n"
                           "    <http://purl.org/dc/terms/created> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2011-10-19T14:51:13Z\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/modified> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2012-04-20T19:52:45Z\"\n"
                           "    ] .";
    RDF rdf = RDF::fromString(inputWithoutLists);
    PurgeRDFBag PurgeRDFBag(&rdf);
    PurgeRDFBag.purge();
    ASSERT_TRUE(RDF::equals(&rdf, expected, "turtle", true));
}

TEST_F(PurgeRDFBagTests, BothWithAndWithoutRdfBagLists) {
    std::string expected = "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
                           "@prefix bqmodel: <http://biomodels.net/model-qualifiers/> .\n"
                           "@prefix bqbiol: <http://biomodels.net/biology-qualifiers/> .\n"
                           "@prefix OMEXlib: <http://omex-library.org/> .\n"
                           "@prefix local: <http://omex-library.org/NewOmex.omex/NewModel.rdf#> .\n"
                           "\n"
                           "<http://omex-library.org/NewOmex.omex/NewModel.xml#_272044>\n"
                           "    bqbiol:hasTaxon <http://identifiers.org/taxonomy/33090> ;\n"
                           "    bqmodel:is <http://identifiers.org/biomodels.db/BIOMD0000000385>, <http://identifiers.org/biomodels.db/MODEL1109270001>, <http://identifiers.org/obo.go/GO:0019253> ;\n"
                           "    bqmodel:isDescribedBy <http://identifiers.org/pubmed/22001849> ;\n"
                           "    <http://purl.org/dc/elements/1.1/creator> [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"EMBL-EBI\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Chelliah\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Vijayalakshmi\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"viji@ebi.ac.uk\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"\"\"Institute of Biochemistry and Biology, University of Potsdam, 14476\n"
                           "                                    Potsdam, Germany\n"
                           "                                \"\"\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Nikoloski\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Zoran\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"nikoloski@mpimp-golm.mpg.de\"\n"
                           "    ], [\n"
                           "        <http://xmlns.com/foaf/0.1/Organization> \"Max-Planck-Institute of Molecular Plant Physiology\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/familyName> \"Arnold\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/givenName> \"Anne\" ;\n"
                           "        <http://xmlns.com/foaf/0.1/mbox> \"arnold@mpimp-golm.mpg.de\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/created> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2011-10-19T14:51:13Z\"\n"
                           "    ] ;\n"
                           "    <http://purl.org/dc/terms/modified> [\n"
                           "        <http://purl.org/dc/terms/W3CDTF> \"2012-04-20T19:52:45Z\"\n"
                           "    ] .";
    RDF rdf = RDF::fromString(fullInput);
    PurgeRDFBag PurgeRDFBag(&rdf);
    PurgeRDFBag.purge();
    ASSERT_TRUE(RDF::equals(&rdf, expected, "turtle", true));
}
