#include <iostream>
#include "omexmeta/OmexMetaCApi.h"

using namespace omexmeta;

const char* getSBMLString(){
    return  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version1/core\" level=\"3\" version=\"1\">\n"
            "  <model metaid=\"MichaelisMenten\" id=\"MichaelisMenten\">\n"
            "    <listOfCompartments>\n"
            "      <compartment id=\"Cell\" metaid=\"Cell\" spatialDimensions=\"3\" constant=\"true\"/>\n"
            "    </listOfCompartments>\n"
            "    <listOfSpecies>\n"
            "      <species id=\"S\" metaid=\"S\" compartment=\"Cell\" initialConcentration=\"100\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
            "      <species id=\"E\" metaid=\"E\" compartment=\"Cell\" initialConcentration=\"0.5\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
            "      <species id=\"SE\" metaid=\"SE\" compartment=\"Cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
            "      <species id=\"P\" metaid=\"P\" compartment=\"Cell\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
            "    </listOfSpecies>\n"
            "    <listOfParameters>\n"
            "      <parameter id=\"kf\" metaid=\"kf\" value=\"0.1\" constant=\"true\"/>\n"
            "      <parameter id=\"kb\" metaid=\"kb\" value=\"0.01\" constant=\"true\"/>\n"
            "      <parameter id=\"kcat\" metaid=\"kcat\" value=\"0.0001\" constant=\"true\"/>\n"
            "    </listOfParameters>\n"
            "    <listOfReactions>\n"
            "      <reaction id=\"R1\" metaid=\"R1\" reversible=\"false\" fast=\"false\">\n"
            "        <listOfReactants>\n"
            "          <speciesReference species=\"S\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "          <speciesReference species=\"E\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "        </listOfReactants>\n"
            "        <listOfProducts>\n"
            "          <speciesReference species=\"SE\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "        </listOfProducts>\n"
            "        <kineticLaw>\n"
            "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
            "            <apply>\n"
            "              <times/>\n"
            "              <ci> kf </ci>\n"
            "              <ci> S </ci>\n"
            "              <ci> E </ci>\n"
            "            </apply>\n"
            "          </math>\n"
            "        </kineticLaw>\n"
            "      </reaction>\n"
            "      <reaction id=\"R2\" metaid=\"R2\" reversible=\"false\" fast=\"false\">\n"
            "        <listOfReactants>\n"
            "          <speciesReference species=\"SE\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "        </listOfReactants>\n"
            "        <listOfProducts>\n"
            "          <speciesReference species=\"S\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "          <speciesReference species=\"E\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "        </listOfProducts>\n"
            "        <kineticLaw>\n"
            "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
            "            <apply>\n"
            "              <times/>\n"
            "              <ci> kb </ci>\n"
            "              <ci> SE </ci>\n"
            "            </apply>\n"
            "          </math>\n"
            "        </kineticLaw>\n"
            "      </reaction>\n"
            "      <reaction id=\"R3\" metaid=\"R3\" reversible=\"false\" fast=\"false\">\n"
            "        <listOfReactants>\n"
            "          <speciesReference species=\"SE\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "        </listOfReactants>\n"
            "        <listOfProducts>\n"
            "          <speciesReference species=\"E\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "          <speciesReference species=\"P\" stoichiometry=\"1\" constant=\"true\"/>\n"
            "        </listOfProducts>\n"
            "        <kineticLaw>\n"
            "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
            "            <apply>\n"
            "              <times/>\n"
            "              <ci> kcat </ci>\n"
            "              <ci> SE </ci>\n"
            "            </apply>\n"
            "          </math>\n"
            "        </kineticLaw>\n"
            "      </reaction>\n"
            "    </listOfReactions>\n"
            "  </model>\n"
            "</sbml>";
}


int main(){

    RDF* rdf_ptr = RDF_new();
    Editor* editor_ptr = RDF_toEditor(rdf_ptr, getSBMLString(), false, true);
    

}