//
// Created by Ciaran on 3/29/2020.
//

#ifndef LIBSEMGEN_SBMLFACTORY_H
#define LIBSEMGEN_SBMLFACTORY_H

#include <utility>
#include <string>
#include <stdexcept>


enum ModelType {
    SBML_ANNOTATED,
    SBML_NOT_ANNOTATED,
    SBML_NOT_ANNOTATED2,
    SBML_Semantic_Extraction_Model,
    SBML_BIOMD204
    SBML_BIOMD366
};

/*
 * Abstract class implemented by all SBML models
 */
class SBMLModel {
public:
    SBMLModel() = default;

    virtual std::string str() = 0;

};

class SBMLAnnotated : SBMLModel {
public:
    SBMLAnnotated() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version2/core\" level=\"3\" version=\"2\">\n"
               "  <model id=\"beta_cell_model\">\n"
               "    <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"molar\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"mole\" exponent=\"1\" scale=\"1\" multiplier=\"1\"/>\n"
               "          <unit kind=\"litre\" exponent=\"-1\" scale=\"1\" multiplier=\"1\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment metaid=\"#cytosol\" id=\"cytosol\" size=\"1\" constant=\"true\"/>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species metaid=\"#glucose\" id=\"glucose\" compartment=\"cytosol\" initialConcentration=\"0\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"glucose_import\" reversible=\"false\">\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"glucose\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <ci> glucose_import_rate </ci>\n"
               "          </math>\n"
               "          <listOfLocalParameters>\n"
               "            <localParameter id=\"glucose_import_rate\" value=\"1\"/>\n"
               "          </listOfLocalParameters>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>\n";
    }
};

class SBMLNotAnnotated : SBMLModel {
public:
    SBMLNotAnnotated() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version2/core\" level=\"3\" version=\"2\">\n"
               "  <model id=\"TestModelNotAnnotated\">\n"
               "    <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"molar\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"mole\" exponent=\"1\" scale=\"1\" multiplier=\"1\"/>\n"
               "          <unit kind=\"litre\" exponent=\"-1\" scale=\"1\" multiplier=\"1\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment metaid=\"#cytosol\" id=\"cytosol\" size=\"1\" constant=\"true\"/>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species metaid=\"#Meta00001\" id=\"X\" compartment=\"cytosol\" initialConcentration=\"10\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Y\" compartment=\"cytosol\" initialConcentration=\"20\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Y\" compartment=\"cytosol\" initialConcentration=\"15\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"X2Y\" reversible=\"false\">\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Y\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> x </ci>\n"
               "              <ci> kx2y </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "          <listOfLocalParameters>\n"
               "            <localParameter id=\"kx2y\" value=\"1\"/>\n"
               "            <localParameter id=\"ky2z\" value=\"1\"/>\n"
               "          </listOfLocalParameters>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"y2z\" reversible=\"false\">\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Z\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> y </ci>\n"
               "              <ci> ky2z </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>\n";
    }
};

class SBMLNotAnnotated2 : SBMLModel {
public:
    SBMLNotAnnotated2() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version2/core\" level=\"3\" version=\"2\">\n"
               "  <model id=\"TestModelNotAnnotated\">\n"
               "    <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"molar\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"mole\" exponent=\"1\" scale=\"1\" multiplier=\"1\"/>\n"
               "          <unit kind=\"litre\" exponent=\"-1\" scale=\"1\" multiplier=\"1\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment metaid=\"#cytosol\" id=\"cytosol\" size=\"1\" constant=\"true\"/>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species metaid=\"#Meta00001\" id=\"X\" compartment=\"cytosol\" initialConcentration=\"10\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Y\" compartment=\"cytosol\" initialConcentration=\"15\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Z\" compartment=\"cytosol\" initialConcentration=\"15\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"X2Y\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference species=\"X\" constant=\"false\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Y\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> X </ci>\n"
               "              <ci> kx2y </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "          <listOfLocalParameters>\n"
               "            <localParameter id=\"kx2y\" value=\"1\"/>\n"
               "            <localParameter id=\"ky2z\" value=\"1\"/>\n"
               "          </listOfLocalParameters>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"y2z\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference species=\"Y\" constant=\"false\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Z\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <speciesReference species=\"X\" constant=\"false\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> X </ci>\n"
               "              <ci> Y </ci>\n"
               "              <ci> ky2z </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>\n";
    }
};

class SBMLSemanticExtractionModel : SBMLModel {
public:
    SBMLSemanticExtractionModel() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version1/core\" level=\"3\" version=\"1\">\n"
               "    <model metaid=\"ToyModel\" id=\"ToyModel\">\n"
               "        <listOfCompartments>\n"
               "            <compartment id=\"cytosol\" metaid=\"comp1\" spatialDimensions=\"3\" size=\"1\" constant=\"true\"/>\n"
               "            <compartment id=\"extraCell\" metaid=\"comp2\" spatialDimensions=\"3\" size=\"10\" constant=\"true\"/>\n"
               "        </listOfCompartments>\n"
               "        <listOfSpecies>\n"
               "            <species id=\"A\" metaid=\"sp_1\" compartment=\"cytosol\" initialConcentration=\"10\" hasOnlySubstanceUnits=\"false\"\n"
               "                     boundaryCondition=\"false\" constant=\"false\">\n"
               "                <annotation>\n"
               "                    <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
               "                             xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "                        <rdf:Description rdf:about=\"#_1\">\n"
               "                            <bqbiol:is>\n"
               "                                <rdf:Bag>\n"
               "                                    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00742\"/>\n"
               "                                </rdf:Bag>\n"
               "                            </bqbiol:is>\n"
               "                        </rdf:Description>\n"
               "                    </rdf:RDF>\n"
               "                </annotation>\n"
               "            </species>\n"
               "            <species id=\"B\" metaid=\"sp_2\" compartment=\"cytosol\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\"\n"
               "                     boundaryCondition=\"false\" constant=\"false\"/>\n"
               "            <species id=\"Ca\" metaid=\"sp_3\" compartment=\"cytosol\" initialConcentration=\"2\" hasOnlySubstanceUnits=\"false\"\n"
               "                     boundaryCondition=\"false\" constant=\"false\"/>\n"
               "            <species id=\"PlasmaCa\" metaid=\"sp_4\" compartment=\"extraCell\" initialConcentration=\"3\"\n"
               "                     hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "            <species id=\"Enzyme\" metaid=\"sp_5\" compartment=\"cytosol\" initialConcentration=\"2\"\n"
               "                     hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "        </listOfSpecies>\n"
               "        <listOfParameters>\n"
               "            <parameter id=\"k1\" value=\"0.1\" constant=\"true\"/>\n"
               "            <parameter id=\"k2\" value=\"0.1\" constant=\"true\"/>\n"
               "        </listOfParameters>\n"
               "        <listOfReactions>\n"
               "            <reaction id=\"r1\" metaid=\"react1\" reversible=\"false\" fast=\"false\">\n"
               "                <listOfReactants>\n"
               "                    <speciesReference species=\"B\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                </listOfReactants>\n"
               "                <listOfProducts>\n"
               "                    <speciesReference species=\"A\" stoichiometry=\"2\" constant=\"true\"/>\n"
               "                </listOfProducts>\n"
               "                <kineticLaw>\n"
               "                    <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "                        <apply>\n"
               "                            <times/>\n"
               "                            <ci>k2</ci>\n"
               "                            <ci>B</ci>\n"
               "                        </apply>\n"
               "                    </math>\n"
               "                </kineticLaw>\n"
               "            </reaction>\n"
               "            <reaction id=\"r2\" metaid=\"react2\" reversible=\"false\" fast=\"false\">\n"
               "                <listOfReactants>\n"
               "                    <speciesReference species=\"Ca\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                    <speciesReference species=\"A\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                </listOfReactants>\n"
               "                <listOfProducts>\n"
               "                    <speciesReference species=\"PlasmaCa\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                </listOfProducts>\n"
               "                <listOfModifiers>\n"
               "                    <modifierSpeciesReference species=\"Enzyme\"/>\n"
               "                </listOfModifiers>\n"
               "                <kineticLaw>\n"
               "                    <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "                        <apply>\n"
               "                            <times/>\n"
               "                            <ci>k2</ci>\n"
               "                            <ci>Ca</ci>\n"
               "                        </apply>\n"
               "                    </math>\n"
               "                </kineticLaw>\n"
               "            </reaction>\n"
               "        </listOfReactions>\n"
               "    </model>\n"
               "</sbml>\n"
               "";
    }
};

class BIOMD204 : SBMLModel {
public:
    BIOMD204() = default;

    std::string str() override {
        return "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level2/version3\" level=\"2\" metaid=\"metaid_0000001\" version=\"3\">\n"
               "  <model id=\"MODEL7957942740\" metaid=\"metaid_0000002\" name=\"Chickarmane2006 - Stem cell switch irreversible\">\n"
               "    <notes>\n"
               "      <body xmlns=\"http://www.w3.org/1999/xhtml\">\n"
               "        <div class=\"dc:title\">Chickarmane2006 - Stem cell switch irreversible</div>\n"
               "            <div class=\"dc:description\">      <p>Kinetic modeling approach of the transcriptional dynamics of the embryonic stem cell switch.</p>\n"
               "                </div>\n"
               "            <div class=\"dc:bibliographicCitation\">      <p>This model is described in the article:</p>\n"
               "                <div class=\"bibo:title\">        <a href=\"http://identifiers.org/pubmed/16978048\" title=\"Access to this publication\">Transcriptional dynamics of the embryonic stem cell switch.</a>\n"
               "                    </div>\n"
               "                <div class=\"bibo:authorList\">Chickarmane V, Troein C, Nuber UA, Sauro HM, Peterson C</div>\n"
               "                <div class=\"bibo:Journal\">PLoS Computational Biology. 2006; 2(9):e123</div>\n"
               "                <p>Abstract:</p>\n"
               "                <div class=\"bibo:abstract\">        <p>Recent ChIP experiments of human and mouse embryonic stem cells have elucidated the architecture of the transcriptional regulatory circuitry responsible for cell determination, which involves the transcription factors OCT4, SOX2, and NANOG. In addition to regulating each other through feedback loops, these genes also regulate downstream target genes involved in the maintenance and differentiation of embryonic stem cells. A search for the OCT4-SOX2-NANOG network motif in other species reveals that it is unique to mammals. With a kinetic modeling approach, we ascribe function to the observed OCT4-SOX2-NANOG network by making plausible assumptions about the interactions between the transcription factors at the gene promoter binding sites and RNA polymerase (RNAP), at each of the three genes as well as at the target genes. We identify a bistable switch in the network, which arises due to several positive feedback loops, and is switched on/off by input environmental signals. The switch stabilizes the expression levels of the three genes, and through their regulatory roles on the downstream target genes, leads to a binary decision: when OCT4, SOX2, and NANOG are expressed and the switch is on, the self-renewal genes are on and the differentiation genes are off. The opposite holds when the switch is off. The model is extremely robust to parameter changes. In addition to providing a self-consistent picture of the transcriptional circuit, the model generates several predictions. Increasing the binding strength of NANOG to OCT4 and SOX2, or increasing its basal transcriptional rate, leads to an irreversible bistable switch: the switch remains on even when the activating signal is removed. Hence, the stem cell can be manipulated to be self-renewing without the requirement of input signals. We also suggest tests that could discriminate between a variety of feedforward regulation architectures of the target genes by OCT4, SOX2, and NANOG.</p>\n"
               "                    </div>\n"
               "                </div>\n"
               "            <div class=\"dc:publisher\">      <p>This model is hosted on        <a href=\"http://www.ebi.ac.uk/biomodels/\">BioModels Database</a>\n"
               "            and identified by:        <a href=\"http://identifiers.org/biomodels.db/MODEL7957942740\">MODEL7957942740</a>\n"
               "            .        </p>\n"
               "                <p>To cite BioModels Database, please use:        <a href=\"http://identifiers.org/pubmed/20587024\" title=\"Latest BioModels Database publication\">BioModels Database: An enhanced, curated and annotated resource for published quantitative kinetic models</a>\n"
               "            .        </p>\n"
               "                </div>\n"
               "            <div class=\"dc:license\">      <p>To the extent possible under law, all copyright and related or neighbouring rights to this encoded model have been dedicated to the public domain worldwide. Please refer to        <a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" title=\"Access to: CC0 1.0 Universal (CC0 1.0), Public Domain Dedication\">CC0 Public Domain Dedication</a>\n"
               "            for more information.        </p>\n"
               "                </div>\n"
               "            </body>\n"
               "      \n"
               "    </notes>\n"
               "    <annotation>\n"
               "      <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "        <rdf:Description rdf:about=\"#metaid_0000002\">\n"
               "    <dc:creator>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Chelliah</vCard:Family>\n"
               "    <vCard:Given>Vijayalakshmi</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>viji@ebi.ac.uk</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>EMBL-EBI</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    \n"
               "    \n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Endler</vCard:Family>\n"
               "    <vCard:Given>Lukas</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>llukas@ebi.ac.uk</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>EMBL-EBI</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Chickarmane</vCard:Family>\n"
               "    <vCard:Given>Vijay</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>vchickar@caltech.edu</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>Keck Graduate Institute, California</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Peterson</vCard:Family>\n"
               "    <vCard:Given>Carsten</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>carsten@thep.lu.se</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>Lund Strategic Research Centre for Stem Cell Biology and Cell Therapy, Lund University, Sweden.</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    </rdf:Bag>\n"
               "    </dc:creator>\n"
               "    <dcterms:created rdf:parseType=\"Resource\">\n"
               "    <dcterms:W3CDTF>2008-11-26T13:10:43Z</dcterms:W3CDTF>\n"
               "    </dcterms:created>\n"
               "    <dcterms:modified rdf:parseType=\"Resource\">\n"
               "    <dcterms:W3CDTF>2013-06-05T16:57:58Z</dcterms:W3CDTF>\n"
               "    </dcterms:modified>\n"
               "    <bqmodel:is>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL7957942740\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqmodel:is>\n"
               "    <bqmodel:is>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000204\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqmodel:is>\n"
               "    <bqmodel:isDescribedBy>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/pubmed/16978048\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqmodel:isDescribedBy>\n"
               "    <bqbiol:hasTaxon>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/9606\"/>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/10090\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:hasTaxon>\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0048863\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "      </rdf:RDF>\n"
               "    </annotation>\n"
               "      <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"substance\" metaid=\"metaid_0000058\" name=\"arb_substance\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"dimensionless\" metaid=\"_147522\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "      <unitDefinition id=\"Volume\" metaid=\"metaid_0000059\" name=\"arb_volume\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"dimensionless\" metaid=\"_147535\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "      <unitDefinition id=\"Time\" metaid=\"metaid_0000060\" name=\"arb_time\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"dimensionless\" metaid=\"_147547\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment id=\"compartment\" metaid=\"metaid_0000035\" size=\"1\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000035\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0005623\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </compartment>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"OCT4_Gene\" initialConcentration=\"0\" metaid=\"metaid_0000036\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000036\">\n"
               "              <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/ensembl/ENSG00000204531\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    \n"
               "    <bqbiol:encodes>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q01860\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:encodes>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"NANOG_Gene\" initialConcentration=\"0\" metaid=\"metaid_0000037\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000037\">\n"
               "              <bqbiol:encodes>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q8N7R0\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:encodes>\n"
               "    \n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/ensembl/ENSG00000176654\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"SOX2_Gene\" initialConcentration=\"0\" metaid=\"metaid_0000038\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000038\">\n"
               "              <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/ensembl/ENSG00000165661\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    \n"
               "    <bqbiol:encodes>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q6ZRP7\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:encodes>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"targetGene\" initialConcentration=\"0.01\" metaid=\"metaid_0000039\"/>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"degradation\" initialConcentration=\"0\" metaid=\"metaid_0000040\"/>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"p53\" initialConcentration=\"0\" metaid=\"metaid_0000041\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000041\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/P04637\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"A\" initialConcentration=\"10\" metaid=\"metaid_0000042\"/>\n"
               "      <species compartment=\"compartment\" id=\"OCT4\" initialConcentration=\"0.01\" metaid=\"metaid_0000043\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000043\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q01860\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"SOX2\" initialConcentration=\"0.01\" metaid=\"metaid_0000044\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000044\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q6ZRP7\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"NANOG\" initialConcentration=\"0.01\" metaid=\"metaid_0000045\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000045\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q8N7R0\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"OCT4_SOX2\" initialConcentration=\"0.1\" metaid=\"metaid_0000046\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000046\">\n"
               "    <bqbiol:hasPart>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q01860\"/>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q6ZRP7\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:hasPart>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"Protein\" initialConcentration=\"0\" metaid=\"metaid_0000047\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfParameters>\n"
               "      <parameter id=\"eta1\" metaid=\"metaid_0000003\" name=\"eta1\" value=\"0.0001\"/>\n"
               "      <parameter id=\"a1\" metaid=\"metaid_0000004\" name=\"a1\" value=\"1\"/>\n"
               "      <parameter id=\"a2\" metaid=\"metaid_0000005\" name=\"a2\" value=\"0.01\"/>\n"
               "      <parameter id=\"a3\" metaid=\"metaid_0000006\" name=\"a3\" value=\"0.5\"/>\n"
               "      <parameter id=\"f\" metaid=\"metaid_0000007\" name=\"f\" value=\"1000\"/>\n"
               "      <parameter id=\"b1\" metaid=\"metaid_0000008\" name=\"b1\" value=\"0.0011\"/>\n"
               "      <parameter id=\"b2\" metaid=\"metaid_0000009\" name=\"b2\" value=\"0.001\"/>\n"
               "      <parameter id=\"b3\" metaid=\"metaid_0000010\" name=\"b3\" value=\"0.001\"/>\n"
               "      <parameter id=\"gamma1\" metaid=\"metaid_0000011\" name=\"gamma1\" value=\"1\"/>\n"
               "      <parameter id=\"eta5\" metaid=\"metaid_0000012\" name=\"eta5\" value=\"0.0001\"/>\n"
               "      <parameter id=\"e1\" metaid=\"metaid_0000013\" name=\"e1\" value=\"0.01\"/>\n"
               "      <parameter id=\"e2\" metaid=\"metaid_0000014\" name=\"e2\" value=\"0.1\"/>\n"
               "      <parameter id=\"f2\" metaid=\"metaid_0000015\" name=\"f2\" value=\"0.001\"/>\n"
               "      <parameter id=\"f1\" metaid=\"metaid_0000016\" name=\"f1\" value=\"0.001\"/>\n"
               "      <parameter id=\"f3\" metaid=\"metaid_0000017\" name=\"f3\" value=\"0.05\"/>\n"
               "      <parameter id=\"gamma2\" metaid=\"metaid_0000018\" name=\"gamma2\" value=\"1\"/>\n"
               "      <parameter id=\"k1c\" metaid=\"metaid_0000019\" name=\"k1c\" value=\"0.05\"/>\n"
               "      <parameter id=\"k2c\" metaid=\"metaid_0000020\" name=\"k2c\" value=\"0.001\"/>\n"
               "      <parameter id=\"k3c\" metaid=\"metaid_0000021\" name=\"k3c\" value=\"5\"/>\n"
               "      <parameter id=\"eta3\" metaid=\"metaid_0000022\" name=\"eta3\" value=\"0.0001\"/>\n"
               "      <parameter id=\"c1\" metaid=\"metaid_0000023\" name=\"c1\" value=\"1\"/>\n"
               "      <parameter id=\"c2\" metaid=\"metaid_0000024\" name=\"c2\" value=\"0.01\"/>\n"
               "      <parameter id=\"c3\" metaid=\"metaid_0000025\" name=\"c3\" value=\"0.5\"/>\n"
               "      <parameter id=\"d1\" metaid=\"metaid_0000026\" name=\"d1\" value=\"0.0011\"/>\n"
               "      <parameter id=\"d2\" metaid=\"metaid_0000027\" name=\"d2\" value=\"0.001\"/>\n"
               "      <parameter id=\"d3\" metaid=\"metaid_0000028\" name=\"d3\" value=\"0.001\"/>\n"
               "      <parameter id=\"gamma3\" metaid=\"metaid_0000029\" name=\"gamma3\" value=\"1\"/>\n"
               "      <parameter id=\"g1\" metaid=\"metaid_0000030\" name=\"g1\" value=\"0.1\"/>\n"
               "      <parameter id=\"eta7\" metaid=\"metaid_0000031\" name=\"eta7\" value=\"0.0001\"/>\n"
               "      <parameter id=\"h1\" metaid=\"metaid_0000032\" name=\"h1\" value=\"0.0011\"/>\n"
               "      <parameter id=\"h2\" metaid=\"metaid_0000033\" name=\"h2\" value=\"1\"/>\n"
               "      <parameter id=\"gamma4\" metaid=\"metaid_0000034\" name=\"gamma4\" value=\"0.01\"/>\n"
               "    </listOfParameters>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"J0\" metaid=\"metaid_0000048\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000048\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147560\" species=\"OCT4_Gene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147573\" species=\"OCT4\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147586\" species=\"A\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147599\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147613\" species=\"NANOG\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_147626\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <ci> eta1 </ci>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> a1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> a2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> a3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta1 </ci>\n"
               "                  <ci> f </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> b1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> b2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> b3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J1\" metaid=\"metaid_0000049\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000049\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147639\" species=\"OCT4\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147652\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147665\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma1 </ci>\n"
               "              <ci> OCT4 </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J2\" metaid=\"metaid_0000050\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000050\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147678\" species=\"NANOG_Gene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147691\" species=\"NANOG\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147704\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147717\" species=\"p53\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_147730\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <ci> eta5 </ci>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> e1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> e2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta5 </ci>\n"
               "                  <ci> f </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> f2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> f1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> f3 </ci>\n"
               "                  <ci> p53 </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J3\" metaid=\"metaid_0000051\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000051\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147743\" species=\"NANOG\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147756\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147769\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma2 </ci>\n"
               "              <ci> NANOG </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J4\" metaid=\"metaid_0000052\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000052\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0006461\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147781\" species=\"OCT4\"/>\n"
               "          <speciesReference metaid=\"_147793\" species=\"SOX2\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147805\" species=\"OCT4_SOX2\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147817\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <minus/>\n"
               "              <apply>\n"
               "                <times/>\n"
               "                <ci> k1c </ci>\n"
               "                <ci> OCT4 </ci>\n"
               "                <ci> SOX2 </ci>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <times/>\n"
               "                <ci> k2c </ci>\n"
               "                <ci> OCT4_SOX2 </ci>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J5\" metaid=\"metaid_0000053\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000053\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147829\" species=\"OCT4_SOX2\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147841\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147853\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> k3c </ci>\n"
               "              <ci> OCT4_SOX2 </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J6\" metaid=\"metaid_0000054\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000054\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147865\" species=\"SOX2_Gene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147877\" species=\"SOX2\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147889\" species=\"A\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147901\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147914\" species=\"NANOG\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_147926\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <ci> eta3 </ci>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> c1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> c2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> c3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta3 </ci>\n"
               "                  <ci> f </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> d1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> d2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> d3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J7\" metaid=\"metaid_0000055\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000055\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147938\" species=\"SOX2\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147950\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147962\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma3 </ci>\n"
               "              <ci> SOX2 </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J8\" metaid=\"metaid_0000056\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000056\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147974\" species=\"targetGene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147986\" species=\"Protein\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147998\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_148010\" species=\"NANOG\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_148022\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> g1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <ci> eta7 </ci>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta7 </ci>\n"
               "                  <ci> f2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> h1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> h2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J9\" metaid=\"metaid_0000057\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000057\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_148034\" species=\"Protein\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_148046\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_148058\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma4 </ci>\n"
               "              <ci> Protein </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>";
    }
};


class BIOMD366 : SBMLModel {
public:
    BIOMD366() = default;

    std::string str() override {
        return "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level2/version4\" level=\"2\" metaid=\"ce1cad6b-9640-4c07-88d4-595a13819703\" version=\"4\">\n"
               "  <model id=\"Model_1\" metaid=\"_0\" name=\"Orfao2008_ThrombinGeneration_AmidolyticActivity\">\n"
               "    <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "        <rdf:Description rdf:about=\"#_0\">\n"
               "\t<dc:creator>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:parseType=\"Resource\">\n"
               "\t<vCard:N rdf:parseType=\"Resource\">\n"
               "\t<vCard:Family>Schubert</vCard:Family>\n"
               "\t<vCard:Given>Michael</vCard:Given>\n"
               "\t</vCard:N>\n"
               "\t<vCard:EMAIL>schubert@ebi.ac.uk</vCard:EMAIL>\n"
               "\t<vCard:ORG rdf:parseType=\"Resource\">\n"
               "\t<vCard:Orgname>EBI</vCard:Orgname>\n"
               "\t</vCard:ORG>\n"
               "\t</rdf:li>\n"
               "\t</rdf:Bag>\n"
               "\t</dc:creator>\n"
               "\t<dcterms:created rdf:parseType=\"Resource\">\n"
               "\t<dcterms:W3CDTF>2011-08-26T16:38:20Z</dcterms:W3CDTF>\n"
               "\t</dcterms:created>\n"
               "\t<dcterms:modified rdf:parseType=\"Resource\">\n"
               "\t<dcterms:W3CDTF>2014-10-09T17:21:48Z</dcterms:W3CDTF>\n"
               "\t</dcterms:modified>\n"
               "\t<bqmodel:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL1108260000\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqmodel:is>\n"
               "\t<bqmodel:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000366\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqmodel:is>\n"
               "\t<bqmodel:isDescribedBy>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/doi/10.1016/j.jmaa.2008.05.060\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqmodel:isDescribedBy>\n"
               "\t<bqmodel:isDerivedFrom>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000358\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqmodel:isDerivedFrom>\n"
               "\t<bqbiol:isVersionOf>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/go/GO:0007596\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:isVersionOf>\n"
               "\t<bqbiol:hasTaxon>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/taxonomy/2759\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:hasTaxon>\n"
               "\t<bqbiol:hasProperty>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/doid/DOID:1287\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:hasProperty>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "      <listOfFunctionDefinitions>\n"
               "      <functionDefinition id=\"HenriMichaelisMenten_irreversible_kcat\" metaid=\"_36\" name=\"Henri-Michaelis-Menten (irreversible) kcat\">\n"
               "        <math xmlns=\"http://www.w3.org/1998/Math/MathML\">        \n"
               "          <lambda>\n"
               "            <bvar>\n"
               "              <ci> kcat </ci>\n"
               "            </bvar>\n"
               "            <bvar>\n"
               "              <ci> enzyme </ci>\n"
               "            </bvar>\n"
               "            <bvar>\n"
               "              <ci> substrate </ci>\n"
               "            </bvar>\n"
               "            <bvar>\n"
               "              <ci> Km </ci>\n"
               "            </bvar>\n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <times/>\n"
               "                <ci> kcat </ci>\n"
               "                <ci> enzyme </ci>\n"
               "                <ci> substrate </ci>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <ci> Km </ci>\n"
               "                <ci> substrate </ci>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </lambda>\n"
               "        </math>\n"
               "            </functionDefinition>\n"
               "    </listOfFunctionDefinitions>\n"
               "    <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"time\" metaid=\"_25db826e-7c70-4aa6-a042-097b74eb3281\" name=\"time\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"second\" metaid=\"_271e452e-ce92-4ce8-9248-04a2f92fe085\" multiplier=\"60\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "      <unitDefinition id=\"substance\" metaid=\"_0addbc79-82f1-48ce-a2a1-8a4851cccdbd\" name=\"substance\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"mole\" metaid=\"c45f080b-2642-46b9-a451-b1b6ecb5c76c\" scale=\"-6\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment id=\"compartment_1\" metaid=\"_35\" name=\"compartment_1\" size=\"1\"/>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species compartment=\"compartment_1\" id=\"X\" initialConcentration=\"0.1999999\" metaid=\"_1\" name=\"X\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_1\">\n"
               "\t<bqbiol:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00742\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:is>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"Xa\" initialConcentration=\"0\" metaid=\"_2\" name=\"Xa\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_2\">\n"
               "\t<bqbiol:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00742\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:is>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"Xa_ATIII\" initialConcentration=\"0\" metaid=\"_3\" name=\"Xa_ATIII\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_3\">\n"
               "\t<bqbiol:hasPart>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00742\"/>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P01008\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:hasPart>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"PL\" initialConcentration=\"0.04999999\" metaid=\"_4\" name=\"PL\"/>\n"
               "      <species compartment=\"compartment_1\" id=\"PT\" initialConcentration=\"0\" metaid=\"_5\" name=\"PT\"/>\n"
               "      <species compartment=\"compartment_1\" id=\"Va\" initialConcentration=\"0\" metaid=\"_6\" name=\"Va\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_6\">\n"
               "\t<bqbiol:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P12259\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:is>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"IIa\" initialConcentration=\"0\" metaid=\"_7\" name=\"IIa\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_7\">\n"
               "\t<bqbiol:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00734\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:is>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"V\" initialConcentration=\"0.02999999\" metaid=\"_8\" name=\"V\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_8\">\n"
               "\t<bqbiol:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P12259\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:is>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"II\" initialConcentration=\"1.4\" metaid=\"_9\" name=\"II\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_9\">\n"
               "\t<bqbiol:is>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00734\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:is>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"IIa_alpha2M\" initialConcentration=\"0\" metaid=\"_10\" name=\"IIa_alpha2M\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_10\">\n"
               "\t<bqbiol:hasPart>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00734\"/>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P01023\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:hasPart>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"IIa_ATIII\" initialConcentration=\"0\" metaid=\"_11\" name=\"IIa_ATIII\">\n"
               "        <annotation>\n"
               "\t<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#_11\">\n"
               "\t<bqbiol:hasPart>\n"
               "\t<rdf:Bag>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00734\"/>\n"
               "\t<rdf:li rdf:resource=\"http://identifiers.org/uniprot/P01008\"/>\n"
               "\t</rdf:Bag>\n"
               "\t</bqbiol:hasPart>\n"
               "\t</rdf:Description>\n"
               "\t\n"
               "\t</rdf:RDF>\n"
               "\t</annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment_1\" id=\"RVV\" initialConcentration=\"0.03\" metaid=\"_12\" name=\"RVV\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfParameters>\n"
               "      <parameter id=\"kcat_X\" metaid=\"_21\" name=\"kcat_X\" sboTerm=\"SBO:0000025\" value=\"239.1\"/>\n"
               "      <parameter id=\"km_X\" metaid=\"_22\" name=\"km_X\" sboTerm=\"SBO:0000371\" value=\"23.65\"/>\n"
               "      <parameter id=\"ki_Xa\" metaid=\"_23\" name=\"ki_Xa\" sboTerm=\"SBO:0000035\" value=\"4.531\"/>\n"
               "      <parameter id=\"k_PT\" metaid=\"_24\" name=\"k_PT\" sboTerm=\"SBO:0000037\" value=\"122.9\"/>\n"
               "      <parameter id=\"k_PL\" metaid=\"_25\" name=\"k_PL\" sboTerm=\"SBO:0000038\" value=\"801.4\"/>\n"
               "      <parameter id=\"kcat_V\" metaid=\"_26\" name=\"kcat_V\" sboTerm=\"SBO:0000025\" value=\"7.844\"/>\n"
               "      <parameter id=\"km_V\" metaid=\"_27\" name=\"km_V\" sboTerm=\"SBO:0000371\" value=\"149.7\"/>\n"
               "      <parameter id=\"kcat_II\" metaid=\"_28\" name=\"kcat_II\" sboTerm=\"SBO:0000025\" value=\"43.87\"/>\n"
               "      <parameter id=\"km_II\" metaid=\"_29\" name=\"km_II\" sboTerm=\"SBO:0000371\" value=\"62.25\"/>\n"
               "      <parameter id=\"kcat_2\" metaid=\"_30\" name=\"kcat_2\" sboTerm=\"SBO:0000025\" value=\"12.4\"/>\n"
               "      <parameter id=\"km_2\" metaid=\"_31\" name=\"km_2\" sboTerm=\"SBO:0000371\" value=\"0.06148\"/>\n"
               "      <parameter id=\"ki_IIaAlpha2M\" metaid=\"_32\" name=\"ki_IIaAlpha2M\" sboTerm=\"SBO:0000035\" value=\"0.1762\"/>\n"
               "      <parameter id=\"ki_IIaATIII\" metaid=\"_33\" name=\"ki_IIaATIII\" sboTerm=\"SBO:0000035\" value=\"0.7859\"/>\n"
               "      <parameter constant=\"false\" id=\"AmAct\" metaid=\"_34\" name=\"AmAct\" value=\"0\"/>\n"
               "    </listOfParameters>\n"
               "    <listOfRules>\n"
               "      <assignmentRule metaid=\"_37\" variable=\"AmAct\">\n"
               "        <math xmlns=\"http://www.w3.org/1998/Math/MathML\">        \n"
               "          <apply>\n"
               "            <plus/>\n"
               "            <ci> IIa </ci>\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <cn> 0.556 </cn>\n"
               "              <ci> IIa_alpha2M </ci>\n"
               "            </apply>\n"
               "          </apply>\n"
               "        </math>\n"
               "            </assignmentRule>\n"
               "    </listOfRules>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"R1\" metaid=\"_13\" name=\"R1\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"b2ed4d58-8f87-45ba-91c8-f6ad8e26b9ed\" sboTerm=\"SBO:0000010\" species=\"X\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_6a6ff937-c739-4680-9ed1-0a89ba42f854\" sboTerm=\"SBO:0000011\" species=\"Xa\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"ed2c312b-4477-41a5-bcd2-ed8740c225fe\" sboTerm=\"SBO:0000461\" species=\"RVV\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"dc492a19-e3b8-486a-8be3-8a350afabce8\" sboTerm=\"SBO:0000028\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <apply>\n"
               "                <ci> HenriMichaelisMenten_irreversible_kcat </ci>\n"
               "                <ci> kcat_X </ci>\n"
               "                <ci> RVV </ci>\n"
               "                <ci> X </ci>\n"
               "                <ci> km_X </ci>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"R2\" metaid=\"_14\" name=\"R2\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"d669520d-9cb5-45a1-9133-8587e2f1120a\" sboTerm=\"SBO:0000010\" species=\"Xa\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_81ecce08-319f-40f5-a7fe-0f8e50b38a53\" sboTerm=\"SBO:0000011\" species=\"Xa_ATIII\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_303cb1c4-c1d0-4e1d-bc4a-df3a9e008655\" sboTerm=\"SBO:0000049\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <ci> ki_Xa </ci>\n"
               "              <ci> Xa </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"R3\" metaid=\"_15\" name=\"R3\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"_52ec55b4-1dc9-47e4-a862-9c8d96e2b6b1\" sboTerm=\"SBO:0000010\" species=\"Va\"/>\n"
               "          <speciesReference metaid=\"_0d4e127b-7ad9-4854-82b9-766371f8f55e\" sboTerm=\"SBO:0000010\" species=\"Xa\"/>\n"
               "          <speciesReference metaid=\"a56a49ac-16a8-4e06-8b8a-ed1c67bbd5c6\" sboTerm=\"SBO:0000010\" species=\"PL\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"dde99a7f-e2d3-4d24-9194-f2d538ebacdd\" sboTerm=\"SBO:0000011\" species=\"PT\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_4c825e27-096f-43fa-a6f4-c6495c4f1da1\" sboTerm=\"SBO:0000122\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <apply>\n"
               "                <minus/>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> k_PT </ci>\n"
               "                  <ci> Va </ci>\n"
               "                  <ci> Xa </ci>\n"
               "                  <ci> PL </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> k_PL </ci>\n"
               "                  <ci> PT </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"R4\" metaid=\"_16\" name=\"R4\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"_4be37855-d94c-4c16-829e-8f7c32789e05\" sboTerm=\"SBO:0000010\" species=\"V\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"a67e0e92-72f1-4905-9336-4b7d4623fae8\" sboTerm=\"SBO:0000011\" species=\"Va\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"c238b3ce-ec20-4e74-b741-03d19fd45ced\" sboTerm=\"SBO:0000461\" species=\"IIa\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"a5f28cd0-3919-4663-b49c-71e48deb7bdf\" sboTerm=\"SBO:0000028\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <apply>\n"
               "                <ci> HenriMichaelisMenten_irreversible_kcat </ci>\n"
               "                <ci> kcat_V </ci>\n"
               "                <ci> IIa </ci>\n"
               "                <ci> V </ci>\n"
               "                <ci> km_V </ci>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"R5\" metaid=\"_17\" name=\"R5\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"f3282ada-dc7a-4e18-a6bd-7dab4819c843\" sboTerm=\"SBO:0000010\" species=\"II\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_034c2073-cc83-4694-a9ef-f266cbaac7d1\" sboTerm=\"SBO:0000011\" species=\"IIa\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"f5f66240-984c-4e93-9fcc-c96883b2f1d6\" sboTerm=\"SBO:0000461\" species=\"PT\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_4f3611c8-105a-4f5e-8574-91816579686e\" sboTerm=\"SBO:0000028\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <apply>\n"
               "                <ci> HenriMichaelisMenten_irreversible_kcat </ci>\n"
               "                <ci> kcat_II </ci>\n"
               "                <ci> PT </ci>\n"
               "                <ci> II </ci>\n"
               "                <ci> km_II </ci>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"R6\" metaid=\"_18\" name=\"R6\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"_5576e5d6-7f5a-443d-a998-77ac7c172535\" sboTerm=\"SBO:0000010\" species=\"II\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_6f2dd8d1-0ecb-4240-9e8d-f72e67b4df3e\" sboTerm=\"SBO:0000011\" species=\"IIa\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"ec9c4101-8fd9-48fe-9fb2-e4981caf3912\" sboTerm=\"SBO:0000461\" species=\"Xa\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"b2c3ee8d-158a-4e75-ad52-69132ea869b9\" sboTerm=\"SBO:0000028\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <apply>\n"
               "                <ci> HenriMichaelisMenten_irreversible_kcat </ci>\n"
               "                <ci> kcat_2 </ci>\n"
               "                <ci> Xa </ci>\n"
               "                <ci> II </ci>\n"
               "                <ci> km_2 </ci>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"R7\" metaid=\"_19\" name=\"R7\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"cd3f3e58-ac0c-4d02-b00d-b01899007537\" sboTerm=\"SBO:0000010\" species=\"IIa\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_956f2f06-2912-439b-b3bc-6ad856c04769\" sboTerm=\"SBO:0000011\" species=\"IIa_alpha2M\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_849c2187-2606-47ff-a560-3faf2f09f5fb\" sboTerm=\"SBO:0000049\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <ci> ki_IIaAlpha2M </ci>\n"
               "              <ci> IIa </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"R8\" metaid=\"_20\" name=\"R8\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference metaid=\"_38f18912-4661-44e2-a56e-45fd3f1dfa0f\" sboTerm=\"SBO:0000010\" species=\"IIa\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_0646e9e5-3113-487f-b2df-a69baa6457e3\" sboTerm=\"SBO:0000011\" species=\"IIa_ATIII\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"efbd2d41-7684-473e-8324-eb0a919d68b9\" sboTerm=\"SBO:0000049\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> compartment_1 </ci>\n"
               "              <ci> ki_IIaATIII </ci>\n"
               "              <ci> IIa </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>";
    }
};


class SBMLFactory {
public:

    static std::string getSBML(ModelType modelType) {
        if (modelType == SBML_ANNOTATED)
            return SBMLAnnotated().str();
        else if (modelType == SBML_NOT_ANNOTATED)
            return SBMLNotAnnotated().str();
        else if (modelType == SBML_NOT_ANNOTATED2)
            return SBMLNotAnnotated2().str();
        else if (modelType == SBML_Semantic_Extraction_Model)
            return SBMLSemanticExtractionModel().str();
        else if (modelType == SBML_BIOMD204)
            return BIOMD204().str();
        else if (modelType == SBML_BIOMD366)
            return BIOMD366().str();
        else {
            throw std::invalid_argument("ModelType is not a valid argument.");
        }
    }

};


#endif //LIBSEMGEN_SBMLFACTORY_H
