//
// Created by Ciaran on 3/29/2020.
//

#ifndef LIBSEMGEN_SBMLFACTORY_H
#define LIBSEMGEN_SBMLFACTORY_H

#include <utility>
#include <string>
#include <stdexcept>


enum ModelType {
    SBML_ANNOTATED,
    SBML_NOT_ANNOTATED,
    SBML_NOT_ANNOTATED2,
    SBML_Semantic_Extraction_Model,
    SBML_BIOMD204
};

/*
 * Abstract class implemented by all SBML models
 */
class SBMLModel {
public:
    SBMLModel() = default;

    virtual std::string str() = 0;

};

class SBMLAnnotated : SBMLModel {
public:
    SBMLAnnotated() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version2/core\" level=\"3\" version=\"2\">\n"
               "  <model id=\"beta_cell_model\">\n"
               "    <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"molar\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"mole\" exponent=\"1\" scale=\"1\" multiplier=\"1\"/>\n"
               "          <unit kind=\"litre\" exponent=\"-1\" scale=\"1\" multiplier=\"1\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment metaid=\"#cytosol\" id=\"cytosol\" size=\"1\" constant=\"true\"/>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species metaid=\"#glucose\" id=\"glucose\" compartment=\"cytosol\" initialConcentration=\"0\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"glucose_import\" reversible=\"false\">\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"glucose\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <ci> glucose_import_rate </ci>\n"
               "          </math>\n"
               "          <listOfLocalParameters>\n"
               "            <localParameter id=\"glucose_import_rate\" value=\"1\"/>\n"
               "          </listOfLocalParameters>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>\n";
    }
};

class SBMLNotAnnotated : SBMLModel {
public:
    SBMLNotAnnotated() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version2/core\" level=\"3\" version=\"2\">\n"
               "  <model id=\"TestModelNotAnnotated\">\n"
               "    <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"molar\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"mole\" exponent=\"1\" scale=\"1\" multiplier=\"1\"/>\n"
               "          <unit kind=\"litre\" exponent=\"-1\" scale=\"1\" multiplier=\"1\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment metaid=\"#cytosol\" id=\"cytosol\" size=\"1\" constant=\"true\"/>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species metaid=\"#Meta00001\" id=\"X\" compartment=\"cytosol\" initialConcentration=\"10\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Y\" compartment=\"cytosol\" initialConcentration=\"20\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Y\" compartment=\"cytosol\" initialConcentration=\"15\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"X2Y\" reversible=\"false\">\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Y\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> x </ci>\n"
               "              <ci> kx2y </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "          <listOfLocalParameters>\n"
               "            <localParameter id=\"kx2y\" value=\"1\"/>\n"
               "            <localParameter id=\"ky2z\" value=\"1\"/>\n"
               "          </listOfLocalParameters>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"y2z\" reversible=\"false\">\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Z\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> y </ci>\n"
               "              <ci> ky2z </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>\n";
    }
};

class SBMLNotAnnotated2 : SBMLModel {
public:
    SBMLNotAnnotated2() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version2/core\" level=\"3\" version=\"2\">\n"
               "  <model id=\"TestModelNotAnnotated\">\n"
               "    <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"molar\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"mole\" exponent=\"1\" scale=\"1\" multiplier=\"1\"/>\n"
               "          <unit kind=\"litre\" exponent=\"-1\" scale=\"1\" multiplier=\"1\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment metaid=\"#cytosol\" id=\"cytosol\" size=\"1\" constant=\"true\"/>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species metaid=\"#Meta00001\" id=\"X\" compartment=\"cytosol\" initialConcentration=\"10\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Y\" compartment=\"cytosol\" initialConcentration=\"15\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "      <species id=\"Z\" compartment=\"cytosol\" initialConcentration=\"15\" substanceUnits=\"molar\" hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"X2Y\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference species=\"X\" constant=\"false\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Y\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> X </ci>\n"
               "              <ci> kx2y </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "          <listOfLocalParameters>\n"
               "            <localParameter id=\"kx2y\" value=\"1\"/>\n"
               "            <localParameter id=\"ky2z\" value=\"1\"/>\n"
               "          </listOfLocalParameters>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"y2z\" reversible=\"false\">\n"
               "        <listOfReactants>\n"
               "          <speciesReference species=\"Y\" constant=\"false\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference species=\"Z\" constant=\"false\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <speciesReference species=\"X\" constant=\"false\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw>\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> X </ci>\n"
               "              <ci> Y </ci>\n"
               "              <ci> ky2z </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "        </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>\n";
    }
};

class SBMLSemanticExtractionModel : SBMLModel {
public:
    SBMLSemanticExtractionModel() = default;

    std::string str() override {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version1/core\" level=\"3\" version=\"1\">\n"
               "    <model metaid=\"ToyModel\" id=\"ToyModel\">\n"
               "        <listOfCompartments>\n"
               "            <compartment id=\"cytosol\" metaid=\"comp1\" spatialDimensions=\"3\" size=\"1\" constant=\"true\"/>\n"
               "            <compartment id=\"extraCell\" metaid=\"comp2\" spatialDimensions=\"3\" size=\"10\" constant=\"true\"/>\n"
               "        </listOfCompartments>\n"
               "        <listOfSpecies>\n"
               "            <species id=\"A\" metaid=\"sp_1\" compartment=\"cytosol\" initialConcentration=\"10\" hasOnlySubstanceUnits=\"false\"\n"
               "                     boundaryCondition=\"false\" constant=\"false\">\n"
               "                <annotation>\n"
               "                    <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
               "                             xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "                        <rdf:Description rdf:about=\"#_1\">\n"
               "                            <bqbiol:is>\n"
               "                                <rdf:Bag>\n"
               "                                    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/P00742\"/>\n"
               "                                </rdf:Bag>\n"
               "                            </bqbiol:is>\n"
               "                        </rdf:Description>\n"
               "                    </rdf:RDF>\n"
               "                </annotation>\n"
               "            </species>\n"
               "            <species id=\"B\" metaid=\"sp_2\" compartment=\"cytosol\" initialConcentration=\"0\" hasOnlySubstanceUnits=\"false\"\n"
               "                     boundaryCondition=\"false\" constant=\"false\"/>\n"
               "            <species id=\"Ca\" metaid=\"sp_3\" compartment=\"cytosol\" initialConcentration=\"2\" hasOnlySubstanceUnits=\"false\"\n"
               "                     boundaryCondition=\"false\" constant=\"false\"/>\n"
               "            <species id=\"PlasmaCa\" metaid=\"sp_4\" compartment=\"extraCell\" initialConcentration=\"3\"\n"
               "                     hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "            <species id=\"Enzyme\" metaid=\"sp_5\" compartment=\"cytosol\" initialConcentration=\"2\"\n"
               "                     hasOnlySubstanceUnits=\"false\" boundaryCondition=\"false\" constant=\"false\"/>\n"
               "        </listOfSpecies>\n"
               "        <listOfParameters>\n"
               "            <parameter id=\"k1\" value=\"0.1\" constant=\"true\"/>\n"
               "            <parameter id=\"k2\" value=\"0.1\" constant=\"true\"/>\n"
               "        </listOfParameters>\n"
               "        <listOfReactions>\n"
               "            <reaction id=\"r1\" metaid=\"react1\" reversible=\"false\" fast=\"false\">\n"
               "                <listOfReactants>\n"
               "                    <speciesReference species=\"B\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                </listOfReactants>\n"
               "                <listOfProducts>\n"
               "                    <speciesReference species=\"A\" stoichiometry=\"2\" constant=\"true\"/>\n"
               "                </listOfProducts>\n"
               "                <kineticLaw>\n"
               "                    <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "                        <apply>\n"
               "                            <times/>\n"
               "                            <ci>k2</ci>\n"
               "                            <ci>B</ci>\n"
               "                        </apply>\n"
               "                    </math>\n"
               "                </kineticLaw>\n"
               "            </reaction>\n"
               "            <reaction id=\"r2\" metaid=\"react2\" reversible=\"false\" fast=\"false\">\n"
               "                <listOfReactants>\n"
               "                    <speciesReference species=\"Ca\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                    <speciesReference species=\"A\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                </listOfReactants>\n"
               "                <listOfProducts>\n"
               "                    <speciesReference species=\"PlasmaCa\" stoichiometry=\"1\" constant=\"true\"/>\n"
               "                </listOfProducts>\n"
               "                <listOfModifiers>\n"
               "                    <modifierSpeciesReference species=\"Enzyme\"/>\n"
               "                </listOfModifiers>\n"
               "                <kineticLaw>\n"
               "                    <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
               "                        <apply>\n"
               "                            <times/>\n"
               "                            <ci>k2</ci>\n"
               "                            <ci>Ca</ci>\n"
               "                        </apply>\n"
               "                    </math>\n"
               "                </kineticLaw>\n"
               "            </reaction>\n"
               "        </listOfReactions>\n"
               "    </model>\n"
               "</sbml>\n"
               "";
    }
};

class BIOMD204 : SBMLModel {
public:
    BIOMD204() = default;

    std::string str() override {
        return "<?xml version='1.0' encoding='UTF-8' standalone='no'?>\n"
               "<sbml xmlns=\"http://www.sbml.org/sbml/level2/version3\" level=\"2\" metaid=\"metaid_0000001\" version=\"3\">\n"
               "  <model id=\"MODEL7957942740\" metaid=\"metaid_0000002\" name=\"Chickarmane2006 - Stem cell switch irreversible\">\n"
               "    <notes>\n"
               "      <body xmlns=\"http://www.w3.org/1999/xhtml\">\n"
               "        <div class=\"dc:title\">Chickarmane2006 - Stem cell switch irreversible</div>\n"
               "            <div class=\"dc:description\">      <p>Kinetic modeling approach of the transcriptional dynamics of the embryonic stem cell switch.</p>\n"
               "                </div>\n"
               "            <div class=\"dc:bibliographicCitation\">      <p>This model is described in the article:</p>\n"
               "                <div class=\"bibo:title\">        <a href=\"http://identifiers.org/pubmed/16978048\" title=\"Access to this publication\">Transcriptional dynamics of the embryonic stem cell switch.</a>\n"
               "                    </div>\n"
               "                <div class=\"bibo:authorList\">Chickarmane V, Troein C, Nuber UA, Sauro HM, Peterson C</div>\n"
               "                <div class=\"bibo:Journal\">PLoS Computational Biology. 2006; 2(9):e123</div>\n"
               "                <p>Abstract:</p>\n"
               "                <div class=\"bibo:abstract\">        <p>Recent ChIP experiments of human and mouse embryonic stem cells have elucidated the architecture of the transcriptional regulatory circuitry responsible for cell determination, which involves the transcription factors OCT4, SOX2, and NANOG. In addition to regulating each other through feedback loops, these genes also regulate downstream target genes involved in the maintenance and differentiation of embryonic stem cells. A search for the OCT4-SOX2-NANOG network motif in other species reveals that it is unique to mammals. With a kinetic modeling approach, we ascribe function to the observed OCT4-SOX2-NANOG network by making plausible assumptions about the interactions between the transcription factors at the gene promoter binding sites and RNA polymerase (RNAP), at each of the three genes as well as at the target genes. We identify a bistable switch in the network, which arises due to several positive feedback loops, and is switched on/off by input environmental signals. The switch stabilizes the expression levels of the three genes, and through their regulatory roles on the downstream target genes, leads to a binary decision: when OCT4, SOX2, and NANOG are expressed and the switch is on, the self-renewal genes are on and the differentiation genes are off. The opposite holds when the switch is off. The model is extremely robust to parameter changes. In addition to providing a self-consistent picture of the transcriptional circuit, the model generates several predictions. Increasing the binding strength of NANOG to OCT4 and SOX2, or increasing its basal transcriptional rate, leads to an irreversible bistable switch: the switch remains on even when the activating signal is removed. Hence, the stem cell can be manipulated to be self-renewing without the requirement of input signals. We also suggest tests that could discriminate between a variety of feedforward regulation architectures of the target genes by OCT4, SOX2, and NANOG.</p>\n"
               "                    </div>\n"
               "                </div>\n"
               "            <div class=\"dc:publisher\">      <p>This model is hosted on        <a href=\"http://www.ebi.ac.uk/biomodels/\">BioModels Database</a>\n"
               "            and identified by:        <a href=\"http://identifiers.org/biomodels.db/MODEL7957942740\">MODEL7957942740</a>\n"
               "            .        </p>\n"
               "                <p>To cite BioModels Database, please use:        <a href=\"http://identifiers.org/pubmed/20587024\" title=\"Latest BioModels Database publication\">BioModels Database: An enhanced, curated and annotated resource for published quantitative kinetic models</a>\n"
               "            .        </p>\n"
               "                </div>\n"
               "            <div class=\"dc:license\">      <p>To the extent possible under law, all copyright and related or neighbouring rights to this encoded model have been dedicated to the public domain worldwide. Please refer to        <a href=\"http://creativecommons.org/publicdomain/zero/1.0/\" title=\"Access to: CC0 1.0 Universal (CC0 1.0), Public Domain Dedication\">CC0 Public Domain Dedication</a>\n"
               "            for more information.        </p>\n"
               "                </div>\n"
               "            </body>\n"
               "      \n"
               "    </notes>\n"
               "    <annotation>\n"
               "      <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "        <rdf:Description rdf:about=\"#metaid_0000002\">\n"
               "    <dc:creator>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Chelliah</vCard:Family>\n"
               "    <vCard:Given>Vijayalakshmi</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>viji@ebi.ac.uk</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>EMBL-EBI</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    \n"
               "    \n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Endler</vCard:Family>\n"
               "    <vCard:Given>Lukas</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>llukas@ebi.ac.uk</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>EMBL-EBI</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Chickarmane</vCard:Family>\n"
               "    <vCard:Given>Vijay</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>vchickar@caltech.edu</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>Keck Graduate Institute, California</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    <rdf:li rdf:parseType=\"Resource\">\n"
               "    <vCard:N rdf:parseType=\"Resource\">\n"
               "    <vCard:Family>Peterson</vCard:Family>\n"
               "    <vCard:Given>Carsten</vCard:Given>\n"
               "    </vCard:N>\n"
               "    <vCard:EMAIL>carsten@thep.lu.se</vCard:EMAIL>\n"
               "    <vCard:ORG rdf:parseType=\"Resource\">\n"
               "    <vCard:Orgname>Lund Strategic Research Centre for Stem Cell Biology and Cell Therapy, Lund University, Sweden.</vCard:Orgname>\n"
               "    </vCard:ORG>\n"
               "    </rdf:li>\n"
               "    </rdf:Bag>\n"
               "    </dc:creator>\n"
               "    <dcterms:created rdf:parseType=\"Resource\">\n"
               "    <dcterms:W3CDTF>2008-11-26T13:10:43Z</dcterms:W3CDTF>\n"
               "    </dcterms:created>\n"
               "    <dcterms:modified rdf:parseType=\"Resource\">\n"
               "    <dcterms:W3CDTF>2013-06-05T16:57:58Z</dcterms:W3CDTF>\n"
               "    </dcterms:modified>\n"
               "    <bqmodel:is>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/MODEL7957942740\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqmodel:is>\n"
               "    <bqmodel:is>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/biomodels.db/BIOMD0000000204\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqmodel:is>\n"
               "    <bqmodel:isDescribedBy>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/pubmed/16978048\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqmodel:isDescribedBy>\n"
               "    <bqbiol:hasTaxon>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/9606\"/>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/taxonomy/10090\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:hasTaxon>\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0048863\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "      </rdf:RDF>\n"
               "    </annotation>\n"
               "      <listOfUnitDefinitions>\n"
               "      <unitDefinition id=\"substance\" metaid=\"metaid_0000058\" name=\"arb_substance\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"dimensionless\" metaid=\"_147522\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "      <unitDefinition id=\"Volume\" metaid=\"metaid_0000059\" name=\"arb_volume\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"dimensionless\" metaid=\"_147535\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "      <unitDefinition id=\"Time\" metaid=\"metaid_0000060\" name=\"arb_time\">\n"
               "        <listOfUnits>\n"
               "          <unit kind=\"dimensionless\" metaid=\"_147547\"/>\n"
               "        </listOfUnits>\n"
               "      </unitDefinition>\n"
               "    </listOfUnitDefinitions>\n"
               "    <listOfCompartments>\n"
               "      <compartment id=\"compartment\" metaid=\"metaid_0000035\" size=\"1\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000035\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0005623\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </compartment>\n"
               "    </listOfCompartments>\n"
               "    <listOfSpecies>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"OCT4_Gene\" initialConcentration=\"0\" metaid=\"metaid_0000036\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000036\">\n"
               "              <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/ensembl/ENSG00000204531\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    \n"
               "    <bqbiol:encodes>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q01860\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:encodes>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"NANOG_Gene\" initialConcentration=\"0\" metaid=\"metaid_0000037\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000037\">\n"
               "              <bqbiol:encodes>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q8N7R0\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:encodes>\n"
               "    \n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/ensembl/ENSG00000176654\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"SOX2_Gene\" initialConcentration=\"0\" metaid=\"metaid_0000038\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000038\">\n"
               "              <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/ensembl/ENSG00000165661\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    \n"
               "    <bqbiol:encodes>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q6ZRP7\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:encodes>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"targetGene\" initialConcentration=\"0.01\" metaid=\"metaid_0000039\"/>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"degradation\" initialConcentration=\"0\" metaid=\"metaid_0000040\"/>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"p53\" initialConcentration=\"0\" metaid=\"metaid_0000041\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000041\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/P04637\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species boundaryCondition=\"true\" compartment=\"compartment\" id=\"A\" initialConcentration=\"10\" metaid=\"metaid_0000042\"/>\n"
               "      <species compartment=\"compartment\" id=\"OCT4\" initialConcentration=\"0.01\" metaid=\"metaid_0000043\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000043\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q01860\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"SOX2\" initialConcentration=\"0.01\" metaid=\"metaid_0000044\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000044\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q6ZRP7\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"NANOG\" initialConcentration=\"0.01\" metaid=\"metaid_0000045\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000045\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q8N7R0\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"OCT4_SOX2\" initialConcentration=\"0.1\" metaid=\"metaid_0000046\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000046\">\n"
               "    <bqbiol:hasPart>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q01860\"/>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/uniprot/Q6ZRP7\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:hasPart>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "            </species>\n"
               "      <species compartment=\"compartment\" id=\"Protein\" initialConcentration=\"0\" metaid=\"metaid_0000047\"/>\n"
               "    </listOfSpecies>\n"
               "    <listOfParameters>\n"
               "      <parameter id=\"eta1\" metaid=\"metaid_0000003\" name=\"eta1\" value=\"0.0001\"/>\n"
               "      <parameter id=\"a1\" metaid=\"metaid_0000004\" name=\"a1\" value=\"1\"/>\n"
               "      <parameter id=\"a2\" metaid=\"metaid_0000005\" name=\"a2\" value=\"0.01\"/>\n"
               "      <parameter id=\"a3\" metaid=\"metaid_0000006\" name=\"a3\" value=\"0.5\"/>\n"
               "      <parameter id=\"f\" metaid=\"metaid_0000007\" name=\"f\" value=\"1000\"/>\n"
               "      <parameter id=\"b1\" metaid=\"metaid_0000008\" name=\"b1\" value=\"0.0011\"/>\n"
               "      <parameter id=\"b2\" metaid=\"metaid_0000009\" name=\"b2\" value=\"0.001\"/>\n"
               "      <parameter id=\"b3\" metaid=\"metaid_0000010\" name=\"b3\" value=\"0.001\"/>\n"
               "      <parameter id=\"gamma1\" metaid=\"metaid_0000011\" name=\"gamma1\" value=\"1\"/>\n"
               "      <parameter id=\"eta5\" metaid=\"metaid_0000012\" name=\"eta5\" value=\"0.0001\"/>\n"
               "      <parameter id=\"e1\" metaid=\"metaid_0000013\" name=\"e1\" value=\"0.01\"/>\n"
               "      <parameter id=\"e2\" metaid=\"metaid_0000014\" name=\"e2\" value=\"0.1\"/>\n"
               "      <parameter id=\"f2\" metaid=\"metaid_0000015\" name=\"f2\" value=\"0.001\"/>\n"
               "      <parameter id=\"f1\" metaid=\"metaid_0000016\" name=\"f1\" value=\"0.001\"/>\n"
               "      <parameter id=\"f3\" metaid=\"metaid_0000017\" name=\"f3\" value=\"0.05\"/>\n"
               "      <parameter id=\"gamma2\" metaid=\"metaid_0000018\" name=\"gamma2\" value=\"1\"/>\n"
               "      <parameter id=\"k1c\" metaid=\"metaid_0000019\" name=\"k1c\" value=\"0.05\"/>\n"
               "      <parameter id=\"k2c\" metaid=\"metaid_0000020\" name=\"k2c\" value=\"0.001\"/>\n"
               "      <parameter id=\"k3c\" metaid=\"metaid_0000021\" name=\"k3c\" value=\"5\"/>\n"
               "      <parameter id=\"eta3\" metaid=\"metaid_0000022\" name=\"eta3\" value=\"0.0001\"/>\n"
               "      <parameter id=\"c1\" metaid=\"metaid_0000023\" name=\"c1\" value=\"1\"/>\n"
               "      <parameter id=\"c2\" metaid=\"metaid_0000024\" name=\"c2\" value=\"0.01\"/>\n"
               "      <parameter id=\"c3\" metaid=\"metaid_0000025\" name=\"c3\" value=\"0.5\"/>\n"
               "      <parameter id=\"d1\" metaid=\"metaid_0000026\" name=\"d1\" value=\"0.0011\"/>\n"
               "      <parameter id=\"d2\" metaid=\"metaid_0000027\" name=\"d2\" value=\"0.001\"/>\n"
               "      <parameter id=\"d3\" metaid=\"metaid_0000028\" name=\"d3\" value=\"0.001\"/>\n"
               "      <parameter id=\"gamma3\" metaid=\"metaid_0000029\" name=\"gamma3\" value=\"1\"/>\n"
               "      <parameter id=\"g1\" metaid=\"metaid_0000030\" name=\"g1\" value=\"0.1\"/>\n"
               "      <parameter id=\"eta7\" metaid=\"metaid_0000031\" name=\"eta7\" value=\"0.0001\"/>\n"
               "      <parameter id=\"h1\" metaid=\"metaid_0000032\" name=\"h1\" value=\"0.0011\"/>\n"
               "      <parameter id=\"h2\" metaid=\"metaid_0000033\" name=\"h2\" value=\"1\"/>\n"
               "      <parameter id=\"gamma4\" metaid=\"metaid_0000034\" name=\"gamma4\" value=\"0.01\"/>\n"
               "    </listOfParameters>\n"
               "    <listOfReactions>\n"
               "      <reaction id=\"J0\" metaid=\"metaid_0000048\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000048\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147560\" species=\"OCT4_Gene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147573\" species=\"OCT4\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147586\" species=\"A\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147599\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147613\" species=\"NANOG\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_147626\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <ci> eta1 </ci>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> a1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> a2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> a3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta1 </ci>\n"
               "                  <ci> f </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> b1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> b2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> b3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J1\" metaid=\"metaid_0000049\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000049\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147639\" species=\"OCT4\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147652\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147665\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma1 </ci>\n"
               "              <ci> OCT4 </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J2\" metaid=\"metaid_0000050\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000050\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147678\" species=\"NANOG_Gene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147691\" species=\"NANOG\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147704\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147717\" species=\"p53\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_147730\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <ci> eta5 </ci>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> e1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> e2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta5 </ci>\n"
               "                  <ci> f </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> f2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> f1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> f3 </ci>\n"
               "                  <ci> p53 </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J3\" metaid=\"metaid_0000051\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000051\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147743\" species=\"NANOG\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147756\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147769\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma2 </ci>\n"
               "              <ci> NANOG </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J4\" metaid=\"metaid_0000052\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000052\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0006461\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147781\" species=\"OCT4\"/>\n"
               "          <speciesReference metaid=\"_147793\" species=\"SOX2\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147805\" species=\"OCT4_SOX2\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147817\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <minus/>\n"
               "              <apply>\n"
               "                <times/>\n"
               "                <ci> k1c </ci>\n"
               "                <ci> OCT4 </ci>\n"
               "                <ci> SOX2 </ci>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <times/>\n"
               "                <ci> k2c </ci>\n"
               "                <ci> OCT4_SOX2 </ci>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J5\" metaid=\"metaid_0000053\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000053\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147829\" species=\"OCT4_SOX2\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147841\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147853\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> k3c </ci>\n"
               "              <ci> OCT4_SOX2 </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J6\" metaid=\"metaid_0000054\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000054\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147865\" species=\"SOX2_Gene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147877\" species=\"SOX2\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147889\" species=\"A\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147901\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_147914\" species=\"NANOG\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_147926\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <ci> eta3 </ci>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> c1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> c2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> c3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta3 </ci>\n"
               "                  <ci> f </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> d1 </ci>\n"
               "                  <ci> A </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> d2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> d3 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J7\" metaid=\"metaid_0000055\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000055\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147938\" species=\"SOX2\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147950\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_147962\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma3 </ci>\n"
               "              <ci> SOX2 </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J8\" metaid=\"metaid_0000056\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000056\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0010467\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_147974\" species=\"targetGene\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_147986\" species=\"Protein\"/>\n"
               "        </listOfProducts>\n"
               "        <listOfModifiers>\n"
               "          <modifierSpeciesReference metaid=\"_147998\" species=\"OCT4_SOX2\"/>\n"
               "          <modifierSpeciesReference metaid=\"_148010\" species=\"NANOG\"/>\n"
               "        </listOfModifiers>\n"
               "        <kineticLaw metaid=\"_148022\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <divide/>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> g1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <ci> eta7 </ci>\n"
               "              </apply>\n"
               "              <apply>\n"
               "                <plus/>\n"
               "                <cn type=\"integer\"> 1 </cn>\n"
               "                <apply>\n"
               "                  <divide/>\n"
               "                  <ci> eta7 </ci>\n"
               "                  <ci> f2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> h1 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                </apply>\n"
               "                <apply>\n"
               "                  <times/>\n"
               "                  <ci> h2 </ci>\n"
               "                  <ci> OCT4_SOX2 </ci>\n"
               "                  <ci> NANOG </ci>\n"
               "                </apply>\n"
               "              </apply>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "      <reaction id=\"J9\" metaid=\"metaid_0000057\" reversible=\"false\">\n"
               "        <annotation>\n"
               "          <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">\n"
               "            <rdf:Description rdf:about=\"#metaid_0000057\">\n"
               "    <bqbiol:isVersionOf>\n"
               "    <rdf:Bag>\n"
               "    <rdf:li rdf:resource=\"http://identifiers.org/obo.go/GO:0030163\"/>\n"
               "    </rdf:Bag>\n"
               "    </bqbiol:isVersionOf>\n"
               "    </rdf:Description>\n"
               "    \n"
               "          </rdf:RDF>\n"
               "        </annotation>\n"
               "              <listOfReactants>\n"
               "          <speciesReference metaid=\"_148034\" species=\"Protein\"/>\n"
               "        </listOfReactants>\n"
               "        <listOfProducts>\n"
               "          <speciesReference metaid=\"_148046\" species=\"degradation\"/>\n"
               "        </listOfProducts>\n"
               "        <kineticLaw metaid=\"_148058\">\n"
               "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">          \n"
               "            <apply>\n"
               "              <times/>\n"
               "              <ci> gamma4 </ci>\n"
               "              <ci> Protein </ci>\n"
               "            </apply>\n"
               "          </math>\n"
               "                </kineticLaw>\n"
               "      </reaction>\n"
               "    </listOfReactions>\n"
               "  </model>\n"
               "</sbml>";
    }
};


class SBMLFactory {
public:

    static std::string getSBML(ModelType modelType) {
        if (modelType == SBML_ANNOTATED)
            return SBMLAnnotated().str();
        else if (modelType == SBML_NOT_ANNOTATED)
            return SBMLNotAnnotated().str();
        else if (modelType == SBML_NOT_ANNOTATED2)
            return SBMLNotAnnotated2().str();
        else if (modelType == SBML_Semantic_Extraction_Model)
            return SBMLSemanticExtractionModel().str();
        else if (modelType == SBML_BIOMD204)
            return BIOMD204().str();
        else {
            throw std::invalid_argument("ModelType is not a valid argument.");
        }
    }

};


#endif //LIBSEMGEN_SBMLFACTORY_H
