@startuml
skinparam monochrome true

enum ModelType {
    SBML_ANNOTATED
    SBML_NOT_ANNOTATED
}

class SBMLFactory {
    + getModel(ModelType type) : SBMLModel*
    + getModelStr(ModelType type) : std::string
}

class SBMLModel{
    + virtual buildModel() : SBMLModel*
}

class AnnotatedSBMLModel {
    + virtual buildModel() : SBMLModel*
}

class NotAnnotatedSBMLModel {
    + virtual buildModel() : SBMLModel*
}

SBMLModel <|-- NotAnnotatedSBMLModel
SBMLModel <|-- AnnotatedSBMLModel


class Client <<Test>>{
    Client(SBMLFactory : ModelType)
}

SBMLFactory <-- Client
ModelType <-- Client
SBMLModel <-- SBMLFactory











@enduml