@startuml
skinparam monochrome true

enum ModelType {
    SBML_ANNOTATED
    SBML_NOT_ANNOTATED
}

class SBMLFactory {
    + getModel(ModelType type) : SemSimSBMLModel*
    + getSBMLString(ModelType type) : std::string
}

class SemSimSBMLModel{
    + virtual buildModel() : SemSimSBMLModel*
}

class AnnotatedSBMLModel {
    + virtual buildModel() : SemSimSBMLModel*
}

class NotAnnotatedSBMLModel {
    + virtual buildModel() : SemSimSBMLModel*
}

SemSimSBMLModel <|-- NotAnnotatedSBMLModel
SemSimSBMLModel <|-- AnnotatedSBMLModel


class Client <<Test>>{
    Client(SBMLFactory : ModelType)
}

SBMLFactory <-- Client
ModelType <-- Client
SemSimSBMLModel <-- SBMLFactory











@enduml