@startuml




left to right direction
:User:
:Reader:
:Writer:
:Creator:
:Querier:
User <|-- Reader
Reader <|-- Writer
Reader <|-- Querier
User <|-- Creator

':application:
':Omex archive:
':Url:
':File:
':web user:
':local user:

(Omex archive) as omex
(Remote file) as remote_file
(Local xml file) as local_file
(Information) as info

'Editor -> remote_file
'Viewer -> remote_file
'Querier -> remote_file
''User -> local_file : creates
''User -> remote_file : wants
'remote_file --> local_file : download
'remote_file --> omex : download

rectangle libCombine {
    (Compress) as compress
    (Decompress) as decompress
    (Manifest) as manifest
}
omex --> decompress
omex <-- compress

(RDF File) as rdf_file

rectangle libomexmeta{
    (RDF) as rdf
'    rdf --> file
'    rdf --> url
'    rdf --> string


'    (Edit/Create) as modify
'    User --> modify
'    modify -- rdf_graph
'    modify -- rdf_file

}



(Read \nfrom file) as file
(Read \nfrom URL) as url
(Read \nfrom string) as string
Reader --> file
Reader --> string
Reader --> url

'decompress --> local_file
'decompress --> rdf_file
'
'local_file --> compress
'rdf_file --> compress
'compress -> omex














@enduml
