macro(SetCrossPlatform name msvc_val linux_val macos_val)
    if (PLATFORM STREQUAL "windows-msvc")
        set(${name} ${msvc_val})
    elseif (PLATFORM STREQUAL "linux")
        set(${name} ${linux_val})
    elseif (PLATFORM STREQUAL "macos")
        set(${name} ${macos_val})
    else ()
        message(FATAL_ERROR "Unknown operating system")
    endif ()

endmacro()