
##########################################################################
# variables for building semsim dependencies
#

set(THIRD_PARTY_DIRS ${CMAKE_SOURCE_DIR}/third_party)

# google test source dir
set(GOOGLETEST_SOURCE ${THIRD_PARTY_DIRS}/googletest)

set(LIBSBML_DEPS_SOURCE_DIR ${THIRD_PARTY_DIRS}/libsbml-dependencies)
set(LIBSBML_DEPS_BINARY_DIR ${LIBSBML_DEPS_SOURCE_DIR}/build)
set(LIBSBML_DEPS_INSTALL_PREFIX ${LIBSBML_DEPS_SOURCE_DIR}/INSTALL)
set(LIBSBML_DEPS_INCLUDE_DIR ${LIBSBML_DEPS_INSTALL_PREFIX}/include)
set(LIBSBML_DEPS_LIB_DIR ${LIBSBML_DEPS_INSTALL_PREFIX}/lib)

set(LIBSBML_SOURCE_DIR ${THIRD_PARTY_DIRS}/libsbml-5.18.0)
set(LIBSBML_BINARY_DIR ${LIBSBML_SOURCE_DIR}/build)
set(LIBSBML_INSTALL_PREFIX ${LIBSBML_SOURCE_DIR}/INSTALL)

set(ZIPPER_SOURCE_DIR ${THIRD_PARTY_DIRS}/zipper)
set(ZIPPER_BINARY_DIR ${ZIPPER_SOURCE_DIR}/build)
set(ZIPPER_INSTALL_PREFIX ${ZIPPER_SOURCE_DIR}/INSTALL)
set(ZIPPER_LIB_DIR "${ZIPPER_INSTALL_PREFIX}/lib")

set(ZLIB_SOURCE_DIR ${THIRD_PARTY_DIRS}/zlib-1.2.11)
set(ZLIB_BINARY_DIR ${ZLIB_SOURCE_DIR}/build)
set(ZLIB_INSTALL_PREFIX ${ZLIB_SOURCE_DIR}/INSTALL)
set(ZLIB_LIB_DIR "${ZLIB_INSTALL_PREFIX}/lib")

set(LIBCOMBINE_SOURCE_DIR ${THIRD_PARTY_DIRS}/libCombine-0.2.3)
set(LIBCOMBINE_BINARY_DIR ${LIBCOMBINE_SOURCE_DIR}/build)
set(LIBCOMBINE_INSTALL_PREFIX ${LIBCOMBINE_SOURCE_DIR}/INSTALL)
set(LIBCOMBINE_LIB_DIR "${LIBCOMBINE_INSTALL_PREFIX}/lib")

set(RAPTOR_SOURCE_DIR ${THIRD_PARTY_DIRS}/raptor2-2.0.15)
set(RAPTOR_BINARY_DIR ${RAPTOR_SOURCE_DIR}/build)
set(RAPTOR_INSTALL_PREFIX ${RAPTOR_SOURCE_DIR}/install_dir)
set(RAPTOR_LIB_DIR "${RAPTOR_INSTALL_PREFIX}/lib")

set(RASQAL_SOURCE_DIR ${THIRD_PARTY_DIRS}/rasqal-0.9.33)
set(RASQAL_BINARY_DIR ${RASQAL_SOURCE_DIR}/build)
set(RASQAL_INSTALL_PREFIX ${RASQAL_SOURCE_DIR}/install_dir)
set(RASQAL_LIB_DIR "${RASQAL_INSTALL_PREFIX}/lib")

set(LIBRDF_SOURCE_DIR ${THIRD_PARTY_DIRS}/redland-1.0.17)
set(LIBRDF_BINARY_DIR ${LIBRDF_SOURCE_DIR}/build)
set(LIBRDF_INSTALL_PREFIX ${LIBRDF_SOURCE_DIR}/install_dir)
set(LIBRDF_LIB_DIR "${LIBRDF_INSTALL_PREFIX}/lib")
